steps:
  # 1. Build the container image
  # This builds both the frontend and backend due to the multi-stage Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA',
        '.',
      ]

  # 2. Extract the binary from the Docker image
  # We create a temporary container, copy the file out, and then remove the container.
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker create --name temp-container ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA
        docker cp temp-container:/app/CitadelDesktop.exe ./CitadelDesktop.exe
        docker rm temp-container

  # 3. Upload the binary to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'storage',
        'cp',
        './CitadelDesktop.exe',
        'gs://${_ARTIFACT_BUCKET}/${_IMAGE_NAME}-${_VERSION}.exe',
      ]


# Define substitution variables
substitutions:
  _REGION: 'us-east1'
  _REPO_NAME: 'us-service-desktop'
  _IMAGE_NAME: 'citadel-ops-desktop'
  _VERSION: '1.0.0'
  _ARTIFACT_BUCKET: 'us-service-ggebot-desktop-bucket'

options:
  logging: CLOUD_LOGGING_ONLY