steps:
  # 1. Build the container image
  # This builds both the frontend and backend due to the multi-stage Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA',
        '.',
      ]

  # 2. Extract all binaries from the Docker image
  # We create a temporary container, copy the files out, and then remove the container.
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker create --name temp-container ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA
        docker cp temp-container:/app/CitadelDesktop.exe ./CitadelDesktop.exe
        docker cp temp-container:/app/CitadelDesktop-macos-amd64 ./CitadelDesktop-macos-amd64
        docker cp temp-container:/app/CitadelDesktop-macos-arm64 ./CitadelDesktop-macos-arm64
        docker rm temp-container

  # 3. Upload the Windows binary to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'storage',
        'cp',
        './CitadelDesktop.exe',
        'gs://${_ARTIFACT_BUCKET}/windows-${_IMAGE_NAME}-${_VERSION}.exe',
      ]

  # 4. Upload the macOS ARM64 binary (Apple Silicon) to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'storage',
        'cp',
        './CitadelDesktop-macos-arm64',
        'gs://${_ARTIFACT_BUCKET}/macos-arm64-${_IMAGE_NAME}-${_VERSION}',
      ]

  # 5. Upload the macOS AMD64 binary (Intel) to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'storage',
        'cp',
        './CitadelDesktop-macos-amd64',
        'gs://${_ARTIFACT_BUCKET}/macos-amd64-${_IMAGE_NAME}-${_VERSION}',
      ]

  # 6. Update Cloud Run backend service with new version environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'services',
        'update',
        '${_BACKEND_SERVICE_NAME}',
        '--region',
        '${_REGION}',
        '--update-env-vars',
        'LATEST_VERSION=${_VERSION},LATEST_DOWNLOAD_URL=https://storage.googleapis.com/${_ARTIFACT_BUCKET}/windows-${_IMAGE_NAME}-${_VERSION}.exe,LATEST_MACOS_ARM64_URL=https://storage.googleapis.com/${_ARTIFACT_BUCKET}/macos-arm64-${_IMAGE_NAME}-${_VERSION},LATEST_MACOS_AMD64_URL=https://storage.googleapis.com/${_ARTIFACT_BUCKET}/macos-amd64-${_IMAGE_NAME}-${_VERSION}',
        '--quiet',
      ]


# Define substitution variables
substitutions:
  _REGION: 'us-east1'
  _REPO_NAME: 'us-service-desktop'
  _IMAGE_NAME: 'citadel-ops-desktop'
  _VERSION: '1.1.1'
  _ARTIFACT_BUCKET: 'us-service-ggebot-desktop-bucket'
  _BACKEND_SERVICE_NAME: 'live-backend-cloud'

options:
  logging: CLOUD_LOGGING_ONLY