package data

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
)

const wodDisplayNamesFileName = "WodDisplayNames.json"

// wodDisplayNamesDoc is generated by Server/cmd/genwoddisplaynames (General's Camp–style
// deco_{type}_name resolution from GGS language packs + buildings.json fallbacks).
type wodDisplayNamesDoc struct {
	LangVersion  string            `json:"langVersion"`
	ItemsVersion string            `json:"itemsVersion"`
	Names        map[string]string `json:"names"`
}

var (
	wodDisplayNamesOnce sync.Once
	wodDisplayNames     map[int]string
	wodDisplayNamesErr  error
)

// WodDisplayName returns a player-facing building name from WodDisplayNames.json when present.
func WodDisplayName(wid int) (string, bool) {
	wodDisplayNamesOnce.Do(func() {
		wodDisplayNames, wodDisplayNamesErr = loadWodDisplayNamesFile()
	})
	if wodDisplayNamesErr != nil || wodDisplayNames == nil {
		return "", false
	}
	s, ok := wodDisplayNames[wid]
	s = trimName(s)
	return s, ok && s != ""
}

func loadWodDisplayNamesFile() (map[int]string, error) {
	base, err := empireDataDir()
	if err != nil {
		return nil, err
	}
	p := filepath.Join(base, wodDisplayNamesFileName)
	b, err := os.ReadFile(p)
	if err != nil {
		if os.IsNotExist(err) {
			return make(map[int]string), nil
		}
		return nil, err
	}
	var doc wodDisplayNamesDoc
	if err := json.Unmarshal(b, &doc); err != nil {
		return nil, err
	}
	out := make(map[int]string, len(doc.Names))
	for ks, name := range doc.Names {
		id, err := strconv.Atoi(ks)
		if err != nil {
			continue
		}
		if n := trimName(name); n != "" {
			out[id] = n
		}
	}
	return out, nil
}

func trimName(s string) string {
	return strings.TrimSpace(s)
}

// WodDisplayNamesPath returns the absolute path to WodDisplayNames.json for tooling.
func WodDisplayNamesPath() (string, error) {
	base, err := empireDataDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(base, wodDisplayNamesFileName), nil
}

// Format: used when map lookup fails entirely
func FormatUnknownWod(wid int) string {
	return fmt.Sprintf("WID %d", wid)
}
