// ============================================
// Unit Type Definitions
// ============================================

export type UnitType = 'melee' | 'range';
export type UnitRole = 'attack' | 'defense';
export type FoodType = 'mead' | 'beef' | 'food';

export interface UnitMeta {
    name: string;
    type: UnitType;
    role: UnitRole;
    food: FoodType;
    consumption: number;
}

export const TROOP_DEFINITIONS: Record<number, string> = {
    5: "Veteran Saber Cleaver",
    6: "Veteran Slingshot",
    7: "Cave Smasher",
    8: "Cave Hunter",
    9: "Veteran Demon Horror",
    10: "Veteran Deathly Horror",
    11: "Veteran Flame Bearer",
    12: "Veteran Composite Bowman",
    13: "Muscle Man",
    14: "Marksman",
    15: "Fruit Pirate",
    18: "Imperial Guardsman",
    19: "Imperial Bowman",
    20: "Imperial Knight",
    21: "Imperial Marksman",
    22: "Berserker",
    23: "Spear Woman",
    34: "Renegade Sai Warrior",
    35: "Renegade Kunai Thrower",
    36: "Renegade Katana Warrior",
    37: "Renegade Bow Master",
    38: "Katana Warrior",
    39: "Bow Master",
    40: "Skeleton Warrior",
    41: "Skeleton Bowman",
    42: "Pumpkin Butcher",
    43: "Raven Chomper",
    48: "Bone Huntress",
    50: "Frost Bowman",
    51: "Master Bone Huntress",
    52: "Master Frost Bowman",
    58: "Star-Spangled Knight",
    59: "Star-Spangled Crossbowman",
    68: "Cave Smasher",
    74: "Cave Hunter",
    75: "Knight of the Elite Guard",
    76: "Crossbowman of the Elite Guard",
    78: "Renegade Cave Smasher",
    79: "Renegade Cave Hunter",
    83: "Forest Warrior",
    84: "Forest Hunter",
    85: "Forest Guardian",
    86: "Forest Bowman",
    92: "Demon Shadow",
    93: "Deathly Shadow",
    100: "Shamrock Huntsman",
    101: "Shamrock Assassin",
    102: "Spring Huntress",
    103: "Spring Footsoldier",
    117: "Fire Witch",
    118: "Bone Rattler",
    119: "Skeletal Hunter",
    120: "Skeletal Scytheman",
    126: "Shapeshifter Legionnaire",
    127: "Shapeshifter Sharpshooter",
    132: "Gnomad Warrior",
    133: "Gnomad Archer",
    134: "Gingerbread Brawler",
    135: "Gingerbread Sniper",
    146: "Knight of the Throne-Watcher",
    147: "Marksman of the Throne-Watcher",
    148: "Relic Axeman",
    149: "Relic Shortbowman",
    150: "Relic Hammerman",
    151: "Relic Longbowman",
    183: "Cultist Brawler",
    184: "Cultist Slingshot",
    185: "Cultist Warrior",
    186: "Cultist Hunter",
    187: "Wilderness Brawler",
    188: "Wilderness Slingshot",
    189: "Wilderness Warrior",
    190: "Wilderness Hunter",
    191: "Corrupted Assassin",
    192: "Corrupted Crossbowman",
    193: "Corrupted Veteran Halberdier",
    194: "Corrupted Veteran Longbowman",
    195: "Shield-Maiden",
    205: "Valkyrie Ranger",
    217: "Protector of the North",
    228: "Valkyrie Sniper",
    277: "Direwolf",
    288: "Easter Championess",
    299: "Valkyrie Huntress",
    308: "Veteran Halberdier",
    309: "Veteran Two-Handed Swordsman",
    311: "Veteran Longbowman",
    312: "Veteran Heavy Crossbowman",
    336: "Guardian of Spring",
    347: "Celestial Marksman",
    358: "Summer Huntress",
    369: "Fruit Breaker",
    409: "Star-Spangled Veteran Demon Horror",
    410: "Star-Spangled Veteran Deathly Horror",
    461: "Summer Marksman",
    479: "Stein Smasher",
    480: "Cask Marksmann",
    481: "Pretzel Guardian",
    482: "Bavarian Brewer",
    485: "Glacial Amazon Warrior",
    486: "Glacial Amazon Archer",
    487: "Glacial Amazon Guardian",
    488: "Glacial Amazon Huntress",
    494: "Christmas Warrior",
    495: "Christmas Archer",
    496: "Christmas Guardian",
    497: "Christmas Huntress",
    498: "Festive Warrior",
    499: "Festive Archer",
    500: "Festive Guardian",
    501: "Festive Huntress",
    502: "Forsaken Maiden",
    503: "Forlorn Ranger",
    513: "Glasswing Archer",
    524: "Flamebreath Berserker",
    535: "Scalebound Guardian",
    546: "Scaleshard Marksman",
    601: "Swordsman",
    602: "Spearman",
    603: "Maceman",
    604: "Halberdier",
    605: "Two-Handed Swordsman",
    606: "Archer",
    607: "Crossbowman",
    608: "Bowman",
    609: "Heavy Crossbowman",
    610: "Longbowman",
    612: "Shadow Maceman",
    613: "Shadow Crossbowman",
    615: "Shadow Ram",
    616: "Shadow Ladder",
    618: "Shadow Bundles",
    619: "Shadow Shields",
    628: "Veteran Spearman",
    630: "Veteran Maceman",
    631: "Veteran Bowman",
    636: "Veteran Crossbowman",
    652: "Armed Citizen",
    655: "Traveling Knight",
    656: "Traveling Crossbowman",
    657: "Shark Tooth Warrior",
    658: "Stone Smasher",
    659: "Prince",
    662: "Skeleton Warrior",
    663: "Skeleton Bowman",
    664: "Crossbowman of the Kingsguard",
    667: "Shadow Rogue",
    668: "Shadow Felon",
    670: "Norseman With Axe",
    671: "Norseman With Bow",
    672: "Knight of the Kingsguard",
    673: "Dragon Claws",
    674: "Dragon Fire",
    675: "Saber Warrior",
    676: "Desert Bowman",
    677: "Norseman With Axe",
    678: "Norseman With Bow",
    679: "Cultist Fanatic",
    680: "Cultist Bowman",
    684: "Marauder",
    685: "Pyromaniac",
    686: "Sentinel of the Kingsguard",
    687: "Scout of the Kingsguard",
    688: "Renegade Saber Warrior",
    689: "Renegade Desert Bowman",
    690: "Renegade Norseman Warrior",
    691: "Renegade Norseman Bowman",
    692: "Renegade Cultist Warrior",
    693: "Renegade Cultist Bowman",
    698: "Cow Berdier",
    699: "Longbow Ox",
    710: "Bear Warrior",
    711: "Bear Bowman",
    712: "Lion Warrior",
    713: "Lion Bowman",
    714: "Demon Horror",
    715: "Deathly Horror",
    716: "Swashbuckler",
    717: "Sail Ripper",
    718: "Tentacle",
    719: "Kraken Head",
    720: "Wolfhound",
    721: "Barbarian",
    722: "Composite Bowman",
    723: "Flame Bearer",
    724: "Veteran Swordsman",
    725: "Khan Guard",
    726: "Saber Cleaver",
    727: "Slingshot",
    728: "Renegade Lancer",
    729: "Renegade Spear Thrower",
    743: "Lancer",
    744: "Spear Thrower",
    746: "Militia",
    747: "Shadow Scoundrel",
    748: "Shadow Wretch",
    749: "Shadow Battering Ram",
    750: "Shadow Siege Tower",
    751: "Shadow Assault Bridge",
    752: "Shadow Mantlet",
    753: "Demon Slayer",
    754: "Assassin",
    759: "Renegade Swashbuckler",
    760: "Renegade Sail Ripper",
    765: "Veteran Marauder",
    766: "Veteran Pyromaniac",
    767: "Renegade Shark Tooth Warrior",
    768: "Renegade Stone Smasher",
    781: "Master Swordsman",
    782: "Master Archer",
    960: "Forest Warrior",
    961: "Forest Hunter",
    962: "Renegade Swashbuckler",
    963: "Renegade Sail Ripper",
    // Leveled units - Shield-Maiden
    196: "Shield-Maiden", 197: "Shield-Maiden", 198: "Shield-Maiden", 199: "Shield-Maiden",
    200: "Shield-Maiden", 201: "Shield-Maiden", 202: "Shield-Maiden", 203: "Shield-Maiden",
    204: "Shield-Maiden", 215: "Shield-Maiden",
    // Leveled units - Valkyrie Ranger
    206: "Valkyrie Ranger", 207: "Valkyrie Ranger", 208: "Valkyrie Ranger", 209: "Valkyrie Ranger",
    210: "Valkyrie Ranger", 211: "Valkyrie Ranger", 212: "Valkyrie Ranger", 213: "Valkyrie Ranger",
    214: "Valkyrie Ranger", 216: "Valkyrie Ranger",
    // Leveled units - Protector of the North
    218: "Protector of the North", 219: "Protector of the North", 220: "Protector of the North",
    221: "Protector of the North", 222: "Protector of the North", 223: "Protector of the North",
    224: "Protector of the North", 225: "Protector of the North", 226: "Protector of the North",
    227: "Protector of the North", 489: "Protector of the North",
    // Leveled units - Valkyrie Sniper
    229: "Valkyrie Sniper", 230: "Valkyrie Sniper", 231: "Valkyrie Sniper", 232: "Valkyrie Sniper",
    233: "Valkyrie Sniper", 234: "Valkyrie Sniper", 235: "Valkyrie Sniper", 236: "Valkyrie Sniper",
    237: "Valkyrie Sniper", 238: "Valkyrie Sniper", 493: "Valkyrie Sniper",
    // Leveled units - Forsaken Maiden
    472: "Forsaken Maiden", 483: "Forsaken Maiden",
    // Leveled units - Forlorn Ranger
    473: "Forlorn Ranger", 484: "Forlorn Ranger",
    // Leveled units - Glasswing Archer
    514: "Glasswing Archer", 515: "Glasswing Archer", 516: "Glasswing Archer", 517: "Glasswing Archer",
    518: "Glasswing Archer", 519: "Glasswing Archer", 520: "Glasswing Archer", 521: "Glasswing Archer",
    522: "Glasswing Archer", 523: "Glasswing Archer",
    // Leveled units - Flamebreath Berserker
    525: "Flamebreath Berserker", 526: "Flamebreath Berserker", 527: "Flamebreath Berserker",
    528: "Flamebreath Berserker", 529: "Flamebreath Berserker", 530: "Flamebreath Berserker",
    531: "Flamebreath Berserker", 532: "Flamebreath Berserker", 533: "Flamebreath Berserker",
    534: "Flamebreath Berserker",
    // Leveled units - Scalebound Guardian
    536: "Scalebound Guardian", 537: "Scalebound Guardian", 538: "Scalebound Guardian",
    539: "Scalebound Guardian", 540: "Scalebound Guardian", 541: "Scalebound Guardian",
    542: "Scalebound Guardian", 543: "Scalebound Guardian", 544: "Scalebound Guardian",
    545: "Scalebound Guardian",
    // Leveled units - Scaleshard Marksman
    547: "Scaleshard Marksman", 548: "Scaleshard Marksman", 549: "Scaleshard Marksman",
    550: "Scaleshard Marksman", 551: "Scaleshard Marksman", 552: "Scaleshard Marksman",
    553: "Scaleshard Marksman", 554: "Scaleshard Marksman", 555: "Scaleshard Marksman",
    556: "Scaleshard Marksman",
    // Leveled units - Swashbuckler
    701: "Swashbuckler", 702: "Swashbuckler",
    // Leveled units - Sail Ripper
    703: "Sail Ripper", 704: "Sail Ripper",
    // Leveled units - Renegade Swashbuckler (levels)
    705: "Renegade Swashbuckler", 706: "Renegade Swashbuckler",
    // Leveled units - Renegade Sail Ripper (levels)
    707: "Renegade Sail Ripper", 708: "Renegade Sail Ripper",
    // Leveled units - Katana Warrior
    820: "Katana Warrior", 821: "Katana Warrior", 822: "Katana Warrior", 823: "Katana Warrior",
    824: "Katana Warrior", 825: "Katana Warrior", 826: "Katana Warrior", 827: "Katana Warrior",
    828: "Katana Warrior", 829: "Katana Warrior",
    // Leveled units - Bow Master
    830: "Bow Master", 831: "Bow Master", 832: "Bow Master", 833: "Bow Master",
    834: "Bow Master", 835: "Bow Master", 836: "Bow Master", 837: "Bow Master",
    838: "Bow Master", 839: "Bow Master",
    // Leveled units - Sai Warrior
    861: "Sai Warrior", 862: "Sai Warrior", 863: "Sai Warrior", 864: "Sai Warrior",
    865: "Sai Warrior", 866: "Sai Warrior", 867: "Sai Warrior", 868: "Sai Warrior",
    869: "Sai Warrior",
    // Leveled units - Kunai Thrower
    871: "Kunai Thrower", 872: "Kunai Thrower", 873: "Kunai Thrower", 874: "Kunai Thrower",
    875: "Kunai Thrower", 876: "Kunai Thrower", 877: "Kunai Thrower", 878: "Kunai Thrower",
    879: "Kunai Thrower",
    // Leveled units - Lancer
    900: "Lancer", 901: "Lancer", 902: "Lancer", 903: "Lancer", 904: "Lancer",
    905: "Lancer", 906: "Lancer", 907: "Lancer", 908: "Lancer", 909: "Lancer",
    // Leveled units - Spear Thrower
    910: "Spear Thrower", 911: "Spear Thrower", 912: "Spear Thrower", 913: "Spear Thrower",
    914: "Spear Thrower", 915: "Spear Thrower", 916: "Spear Thrower", 917: "Spear Thrower",
    918: "Spear Thrower", 919: "Spear Thrower",
    // Leveled units - Veteran Saber Cleaver
    940: "Veteran Saber Cleaver", 941: "Veteran Saber Cleaver", 942: "Veteran Saber Cleaver",
    943: "Veteran Saber Cleaver", 944: "Veteran Saber Cleaver", 945: "Veteran Saber Cleaver",
    946: "Veteran Saber Cleaver", 947: "Veteran Saber Cleaver", 948: "Veteran Saber Cleaver",
    949: "Veteran Saber Cleaver",
    // Leveled units - Veteran Slingshot
    950: "Veteran Slingshot", 951: "Veteran Slingshot", 952: "Veteran Slingshot",
    953: "Veteran Slingshot", 954: "Veteran Slingshot", 955: "Veteran Slingshot",
    956: "Veteran Slingshot", 957: "Veteran Slingshot", 958: "Veteran Slingshot",
    959: "Veteran Slingshot",
    // Leveled units - Veteran Halberdier
    2000: "Veteran Halberdier", 2001: "Veteran Halberdier", 2002: "Veteran Halberdier",
    2003: "Veteran Halberdier", 2004: "Veteran Halberdier", 2005: "Veteran Halberdier",
    2006: "Veteran Halberdier", 2007: "Veteran Halberdier", 2008: "Veteran Halberdier",
    2009: "Veteran Halberdier",
    // Leveled units - Veteran Two-Handed Swordsman
    2010: "Veteran Two-Handed Swordsman", 2011: "Veteran Two-Handed Swordsman",
    2012: "Veteran Two-Handed Swordsman", 2013: "Veteran Two-Handed Swordsman",
    2014: "Veteran Two-Handed Swordsman", 2015: "Veteran Two-Handed Swordsman",
    2016: "Veteran Two-Handed Swordsman", 2017: "Veteran Two-Handed Swordsman",
    2018: "Veteran Two-Handed Swordsman", 2019: "Veteran Two-Handed Swordsman",
    // Leveled units - Relic Axeman
    2020: "Relic Axeman", 2021: "Relic Axeman", 2022: "Relic Axeman", 2023: "Relic Axeman",
    2024: "Relic Axeman", 2025: "Relic Axeman", 2026: "Relic Axeman", 2027: "Relic Axeman",
    2028: "Relic Axeman", 2029: "Relic Axeman",
    // Leveled units - Relic Hammerman
    2030: "Relic Hammerman", 2031: "Relic Hammerman", 2032: "Relic Hammerman",
    2033: "Relic Hammerman", 2034: "Relic Hammerman", 2035: "Relic Hammerman",
    2036: "Relic Hammerman", 2037: "Relic Hammerman", 2038: "Relic Hammerman",
    2039: "Relic Hammerman",
    // Leveled units - Veteran Longbowman
    2040: "Veteran Longbowman", 2041: "Veteran Longbowman", 2042: "Veteran Longbowman",
    2043: "Veteran Longbowman", 2044: "Veteran Longbowman", 2045: "Veteran Longbowman",
    2046: "Veteran Longbowman", 2047: "Veteran Longbowman", 2048: "Veteran Longbowman",
    2049: "Veteran Longbowman",
    // Leveled units - Veteran Heavy Crossbowman
    2050: "Veteran Heavy Crossbowman", 2051: "Veteran Heavy Crossbowman",
    2052: "Veteran Heavy Crossbowman", 2053: "Veteran Heavy Crossbowman",
    2054: "Veteran Heavy Crossbowman", 2055: "Veteran Heavy Crossbowman",
    2056: "Veteran Heavy Crossbowman", 2057: "Veteran Heavy Crossbowman",
    2058: "Veteran Heavy Crossbowman", 2059: "Veteran Heavy Crossbowman",
    // Leveled units - Relic Shortbowman
    2060: "Relic Shortbowman", 2061: "Relic Shortbowman", 2062: "Relic Shortbowman",
    2063: "Relic Shortbowman", 2064: "Relic Shortbowman", 2065: "Relic Shortbowman",
    2066: "Relic Shortbowman", 2067: "Relic Shortbowman", 2068: "Relic Shortbowman",
    2069: "Relic Shortbowman",
    // Leveled units - Relic Longbowman
    2070: "Relic Longbowman", 2071: "Relic Longbowman", 2072: "Relic Longbowman",
    2073: "Relic Longbowman", 2074: "Relic Longbowman", 2075: "Relic Longbowman",
    2076: "Relic Longbowman", 2077: "Relic Longbowman", 2078: "Relic Longbowman",
    2079: "Relic Longbowman",
};

export const TOOL_DEFINITIONS: Record<number, string> = {
};

// ============================================
// TROOP_METADATA
// ============================================
export const TROOP_METADATA: Record<number, UnitMeta> = {
    5: { name: "Veteran Saber Cleaver", type: "melee", role: "attack", food: "food", consumption: 4 },
    6: { name: "Veteran Slingshot", type: "range", role: "attack", food: "food", consumption: 4 },
    7: { name: "Cave Smasher", type: "melee", role: "attack", food: "food", consumption: 0 },
    8: { name: "Cave Hunter", type: "range", role: "attack", food: "food", consumption: 0 },
    9: { name: "Veteran Demon Horror", type: "melee", role: "attack", food: "food", consumption: 5 },
    10: { name: "Veteran Deathly Horror", type: "range", role: "attack", food: "food", consumption: 5 },
    11: { name: "Veteran Flame Bearer", type: "melee", role: "defense", food: "food", consumption: 3 },
    12: { name: "Veteran Composite Bowman", type: "range", role: "defense", food: "food", consumption: 3 },
    13: { name: "Muscle Man", type: "melee", role: "attack", food: "food", consumption: 0 },
    14: { name: "Marksman", type: "range", role: "attack", food: "food", consumption: 0 },
    15: { name: "Fruit Pirate", type: "melee", role: "attack", food: "mead", consumption: 2 },
    18: { name: "Imperial Guardsman", type: "melee", role: "attack", food: "food", consumption: 4 },
    19: { name: "Imperial Bowman", type: "range", role: "attack", food: "food", consumption: 4 },
    20: { name: "Imperial Knight", type: "melee", role: "attack", food: "food", consumption: 4 },
    21: { name: "Imperial Marksman", type: "range", role: "attack", food: "food", consumption: 4 },
    22: { name: "Berserker", type: "melee", role: "attack", food: "food", consumption: 4 },
    23: { name: "Spear Woman", type: "range", role: "attack", food: "food", consumption: 4 },
    34: { name: "Renegade Sai Warrior", type: "melee", role: "attack", food: "food", consumption: 0 },
    35: { name: "Renegade Kunai Thrower", type: "range", role: "attack", food: "food", consumption: 4 },
    36: { name: "Renegade Katana Warrior", type: "melee", role: "defense", food: "food", consumption: 3 },
    37: { name: "Renegade Bow Master", type: "range", role: "defense", food: "food", consumption: 3 },
    38: { name: "Katana Warrior", type: "melee", role: "defense", food: "food", consumption: 0 },
    39: { name: "Bow Master", type: "range", role: "defense", food: "food", consumption: 3 },
    40: { name: "Skeleton Warrior", type: "melee", role: "attack", food: "food", consumption: 5 },
    41: { name: "Skeleton Bowman", type: "range", role: "attack", food: "food", consumption: 5 },
    42: { name: "Pumpkin Butcher", type: "melee", role: "attack", food: "food", consumption: 4 },
    43: { name: "Raven Chomper", type: "range", role: "attack", food: "food", consumption: 4 },
    48: { name: "Bone Huntress", type: "melee", role: "attack", food: "food", consumption: 4 },
    50: { name: "Frost Bowman", type: "range", role: "attack", food: "food", consumption: 4 },
    51: { name: "Master Bone Huntress", type: "melee", role: "attack", food: "food", consumption: 5 },
    52: { name: "Master Frost Bowman", type: "range", role: "attack", food: "food", consumption: 5 },
    58: { name: "Star-Spangled Knight", type: "melee", role: "attack", food: "food", consumption: 0 },
    59: { name: "Star-Spangled Crossbowman", type: "range", role: "attack", food: "food", consumption: 0 },
    68: { name: "Cave Smasher", type: "melee", role: "attack", food: "food", consumption: 0 },
    74: { name: "Cave Hunter", type: "range", role: "attack", food: "food", consumption: 0 },
    75: { name: "Knight of the Elite Guard", type: "melee", role: "attack", food: "food", consumption: 0 },
    76: { name: "Crossbowman of the Elite Guard", type: "melee", role: "attack", food: "food", consumption: 0 },
    78: { name: "Renegade Cave Smasher", type: "melee", role: "attack", food: "food", consumption: 0 },
    79: { name: "Renegade Cave Hunter", type: "range", role: "attack", food: "food", consumption: 0 },
    83: { name: "Forest Warrior", type: "melee", role: "attack", food: "food", consumption: 5 },
    84: { name: "Forest Hunter", type: "range", role: "attack", food: "food", consumption: 5 },
    85: { name: "Forest Guardian", type: "melee", role: "defense", food: "food", consumption: 0 },
    86: { name: "Forest Bowman", type: "range", role: "defense", food: "food", consumption: 3 },
    92: { name: "Demon Shadow", type: "melee", role: "attack", food: "food", consumption: 0 },
    93: { name: "Deathly Shadow", type: "range", role: "attack", food: "food", consumption: 0 },
    100: { name: "Shamrock Huntsman", type: "melee", role: "defense", food: "food", consumption: 0 },
    101: { name: "Shamrock Assassin", type: "range", role: "defense", food: "food", consumption: 0 },
    102: { name: "Spring Huntress", type: "melee", role: "defense", food: "food", consumption: 3 },
    103: { name: "Spring Footsoldier", type: "range", role: "defense", food: "food", consumption: 3 },
    117: { name: "Fire Witch", type: "melee", role: "attack", food: "food", consumption: 0 },
    118: { name: "Bone Rattler", type: "melee", role: "attack", food: "food", consumption: 0 },
    119: { name: "Skeletal Hunter", type: "range", role: "defense", food: "food", consumption: 0 },
    120: { name: "Skeletal Scytheman", type: "melee", role: "defense", food: "food", consumption: 0 },
    126: { name: "Shapeshifter Legionnaire", type: "melee", role: "defense", food: "food", consumption: 0 },
    127: { name: "Shapeshifter Sharpshooter", type: "range", role: "defense", food: "food", consumption: 0 },
    132: { name: "Gnomad Warrior", type: "melee", role: "attack", food: "food", consumption: 0 },
    133: { name: "Gnomad Archer", type: "range", role: "attack", food: "food", consumption: 0 },
    134: { name: "Gingerbread Brawler", type: "melee", role: "defense", food: "food", consumption: 0 },
    135: { name: "Gingerbread Sniper", type: "range", role: "defense", food: "food", consumption: 0 },
    146: { name: "Knight of the Throne-Watcher", type: "melee", role: "defense", food: "food", consumption: 3 },
    147: { name: "Marksman of the Throne-Watcher", type: "range", role: "defense", food: "food", consumption: 3 },
    148: { name: "Relic Axeman", type: "melee", role: "attack", food: "food", consumption: 5 },
    149: { name: "Relic Shortbowman", type: "range", role: "attack", food: "food", consumption: 5 },
    150: { name: "Relic Hammerman", type: "melee", role: "defense", food: "food", consumption: 4 },
    151: { name: "Relic Longbowman", type: "range", role: "defense", food: "food", consumption: 4 },
    183: { name: "Cultist Brawler", type: "melee", role: "defense", food: "food", consumption: 0 },
    184: { name: "Cultist Slingshot", type: "range", role: "defense", food: "food", consumption: 0 },
    185: { name: "Cultist Warrior", type: "melee", role: "attack", food: "food", consumption: 0 },
    186: { name: "Cultist Hunter", type: "range", role: "defense", food: "food", consumption: 0 },
    187: { name: "Wilderness Brawler", type: "melee", role: "attack", food: "food", consumption: 0 },
    188: { name: "Wilderness Slingshot", type: "melee", role: "attack", food: "food", consumption: 0 },
    189: { name: "Wilderness Warrior", type: "melee", role: "attack", food: "food", consumption: 0 },
    190: { name: "Wilderness Hunter", type: "melee", role: "attack", food: "food", consumption: 0 },
    191: { name: "Corrupted Assassin", type: "melee", role: "defense", food: "food", consumption: 0 },
    192: { name: "Corrupted Crossbowman", type: "range", role: "defense", food: "food", consumption: 0 },
    193: { name: "Corrupted Veteran Halberdier", type: "melee", role: "attack", food: "food", consumption: 0 },
    194: { name: "Corrupted Veteran Longbowman", type: "melee", role: "attack", food: "food", consumption: 0 },
    195: { name: "Shield-Maiden", type: "melee", role: "attack", food: "mead", consumption: 2 },
    205: { name: "Valkyrie Ranger", type: "range", role: "attack", food: "mead", consumption: 2 },
    217: { name: "Protector of the North", type: "melee", role: "defense", food: "mead", consumption: 2 },
    228: { name: "Valkyrie Sniper", type: "range", role: "defense", food: "mead", consumption: 2 },
    277: { name: "Direwolf", type: "melee", role: "attack", food: "food", consumption: 3 },
    288: { name: "Easter Championess", type: "melee", role: "attack", food: "mead", consumption: 2 },
    299: { name: "Valkyrie Huntress", type: "range", role: "attack", food: "mead", consumption: 2 },
    308: { name: "Veteran Halberdier", type: "melee", role: "defense", food: "food", consumption: 3 },
    309: { name: "Veteran Two-Handed Swordsman", type: "melee", role: "attack", food: "food", consumption: 4 },
    311: { name: "Veteran Longbowman", type: "range", role: "defense", food: "food", consumption: 3 },
    312: { name: "Veteran Heavy Crossbowman", type: "range", role: "attack", food: "food", consumption: 4 },
    336: { name: "Guardian of Spring", type: "melee", role: "defense", food: "mead", consumption: 2 },
    347: { name: "Celestial Marksman", type: "range", role: "defense", food: "mead", consumption: 2 },
    358: { name: "Summer Huntress", type: "range", role: "attack", food: "mead", consumption: 2 },
    369: { name: "Fruit Breaker", type: "melee", role: "defense", food: "mead", consumption: 2 },
    409: { name: "Star-Spangled Veteran Demon Horror", type: "melee", role: "attack", food: "food", consumption: 5 },
    410: { name: "Star-Spangled Veteran Deathly Horror", type: "range", role: "attack", food: "food", consumption: 5 },
    461: { name: "Summer Marksman", type: "range", role: "defense", food: "mead", consumption: 2 },
    479: { name: "Stein Smasher", type: "melee", role: "attack", food: "mead", consumption: 2 },
    480: { name: "Cask Marksmann", type: "range", role: "attack", food: "mead", consumption: 2 },
    481: { name: "Pretzel Guardian", type: "melee", role: "defense", food: "mead", consumption: 2 },
    482: { name: "Bavarian Brewer", type: "range", role: "defense", food: "mead", consumption: 2 },
    485: { name: "Glacial Amazon Warrior", type: "melee", role: "attack", food: "mead", consumption: 2 },
    486: { name: "Glacial Amazon Archer", type: "melee", role: "attack", food: "mead", consumption: 2 },
    487: { name: "Glacial Amazon Guardian", type: "melee", role: "defense", food: "mead", consumption: 2 },
    488: { name: "Glacial Amazon Huntress", type: "range", role: "defense", food: "mead", consumption: 2 },
    494: { name: "Christmas Warrior", type: "melee", role: "attack", food: "mead", consumption: 2 },
    495: { name: "Christmas Archer", type: "range", role: "attack", food: "mead", consumption: 2 },
    496: { name: "Christmas Guardian", type: "melee", role: "defense", food: "mead", consumption: 2 },
    497: { name: "Christmas Huntress", type: "range", role: "defense", food: "mead", consumption: 2 },
    498: { name: "Festive Warrior", type: "melee", role: "attack", food: "food", consumption: 0 },
    499: { name: "Festive Archer", type: "melee", role: "attack", food: "food", consumption: 0 },
    500: { name: "Festive Guardian", type: "melee", role: "attack", food: "food", consumption: 0 },
    501: { name: "Festive Huntress", type: "melee", role: "attack", food: "food", consumption: 0 },
    502: { name: "Forsaken Maiden", type: "melee", role: "attack", food: "mead", consumption: 2 },
    503: { name: "Forlorn Ranger", type: "range", role: "attack", food: "mead", consumption: 2 },
    513: { name: "Glasswing Archer", type: "range", role: "attack", food: "beef", consumption: 2 },
    524: { name: "Flamebreath Berserker", type: "melee", role: "attack", food: "beef", consumption: 2 },
    535: { name: "Scalebound Guardian", type: "melee", role: "attack", food: "beef", consumption: 2 },
    546: { name: "Scaleshard Marksman", type: "range", role: "attack", food: "beef", consumption: 2 },
    601: { name: "Swordsman", type: "melee", role: "attack", food: "food", consumption: 3 },
    602: { name: "Spearman", type: "melee", role: "attack", food: "food", consumption: 2 },
    603: { name: "Maceman", type: "melee", role: "attack", food: "food", consumption: 2 },
    604: { name: "Halberdier", type: "melee", role: "defense", food: "food", consumption: 3 },
    605: { name: "Two-Handed Swordsman", type: "melee", role: "attack", food: "food", consumption: 0 },
    606: { name: "Archer", type: "range", role: "defense", food: "food", consumption: 2 },
    607: { name: "Crossbowman", type: "range", role: "attack", food: "food", consumption: 2 },
    608: { name: "Bowman", type: "range", role: "attack", food: "food", consumption: 2 },
    609: { name: "Heavy Crossbowman", type: "range", role: "attack", food: "food", consumption: 4 },
    610: { name: "Longbowman", type: "range", role: "defense", food: "food", consumption: 3 },
    612: { name: "Shadow Maceman", type: "melee", role: "attack", food: "food", consumption: 0 },
    613: { name: "Shadow Crossbowman", type: "range", role: "attack", food: "food", consumption: 0 },
    615: { name: "Shadow Ram", type: "melee", role: "attack", food: "food", consumption: 0 },
    616: { name: "Shadow Ladder", type: "melee", role: "attack", food: "food", consumption: 0 },
    618: { name: "Shadow Bundles", type: "melee", role: "attack", food: "food", consumption: 0 },
    619: { name: "Shadow Shields", type: "melee", role: "attack", food: "food", consumption: 0 },
    628: { name: "Veteran Spearman", type: "melee", role: "defense", food: "food", consumption: 3 },
    630: { name: "Veteran Maceman", type: "melee", role: "attack", food: "food", consumption: 4 },
    631: { name: "Veteran Bowman", type: "range", role: "defense", food: "food", consumption: 3 },
    636: { name: "Veteran Crossbowman", type: "range", role: "attack", food: "food", consumption: 4 },
    652: { name: "Armed Citizen", type: "melee", role: "defense", food: "food", consumption: 0 },
    655: { name: "Traveling Knight", type: "melee", role: "attack", food: "food", consumption: 4 },
    656: { name: "Traveling Crossbowman", type: "range", role: "attack", food: "food", consumption: 4 },
    657: { name: "Shark Tooth Warrior", type: "melee", role: "attack", food: "food", consumption: 0 },
    658: { name: "Stone Smasher", type: "range", role: "attack", food: "food", consumption: 0 },
    659: { name: "Prince", type: "melee", role: "defense", food: "food", consumption: 2 },
    662: { name: "Skeleton Warrior", type: "melee", role: "attack", food: "food", consumption: 5 },
    663: { name: "Skeleton Bowman", type: "range", role: "attack", food: "food", consumption: 5 },
    664: { name: "Crossbowman of the Kingsguard", type: "melee", role: "attack", food: "food", consumption: 0 },
    667: { name: "Shadow Rogue", type: "melee", role: "attack", food: "food", consumption: 0 },
    668: { name: "Shadow Felon", type: "range", role: "attack", food: "food", consumption: 0 },
    670: { name: "Norseman With Axe", type: "melee", role: "attack", food: "food", consumption: 0 },
    671: { name: "Norseman With Bow", type: "range", role: "attack", food: "food", consumption: 0 },
    672: { name: "Knight of the Kingsguard", type: "melee", role: "attack", food: "food", consumption: 0 },
    673: { name: "Dragon Claws", type: "melee", role: "defense", food: "food", consumption: 0 },
    674: { name: "Dragon Fire", type: "range", role: "defense", food: "food", consumption: 0 },
    675: { name: "Saber Warrior", type: "melee", role: "attack", food: "food", consumption: 4 },
    676: { name: "Desert Bowman", type: "range", role: "attack", food: "food", consumption: 4 },
    677: { name: "Norseman With Axe", type: "melee", role: "attack", food: "food", consumption: 0 },
    678: { name: "Norseman With Bow", type: "range", role: "attack", food: "food", consumption: 0 },
    679: { name: "Cultist Fanatic", type: "melee", role: "attack", food: "food", consumption: 4 },
    680: { name: "Cultist Bowman", type: "range", role: "attack", food: "food", consumption: 4 },
    684: { name: "Marauder", type: "melee", role: "attack", food: "food", consumption: 4 },
    685: { name: "Pyromaniac", type: "melee", role: "attack", food: "food", consumption: 4 },
    686: { name: "Sentinel of the Kingsguard", type: "melee", role: "attack", food: "food", consumption: 0 },
    687: { name: "Scout of the Kingsguard", type: "melee", role: "attack", food: "food", consumption: 0 },
    688: { name: "Renegade Saber Warrior", type: "melee", role: "attack", food: "food", consumption: 4 },
    689: { name: "Renegade Desert Bowman", type: "range", role: "attack", food: "food", consumption: 4 },
    690: { name: "Renegade Norseman Warrior", type: "melee", role: "attack", food: "food", consumption: 4 },
    691: { name: "Renegade Norseman Bowman", type: "range", role: "attack", food: "food", consumption: 4 },
    692: { name: "Renegade Cultist Warrior", type: "melee", role: "attack", food: "food", consumption: 4 },
    693: { name: "Renegade Cultist Bowman", type: "range", role: "attack", food: "food", consumption: 4 },
    698: { name: "Cow Berdier", type: "melee", role: "attack", food: "food", consumption: 0 },
    699: { name: "Longbow Ox", type: "range", role: "attack", food: "food", consumption: 0 },
    710: { name: "Bear Warrior", type: "melee", role: "attack", food: "food", consumption: 4 },
    711: { name: "Bear Bowman", type: "range", role: "attack", food: "food", consumption: 4 },
    712: { name: "Lion Warrior", type: "melee", role: "attack", food: "food", consumption: 4 },
    713: { name: "Lion Bowman", type: "range", role: "attack", food: "food", consumption: 4 },
    714: { name: "Demon Horror", type: "melee", role: "attack", food: "food", consumption: 5 },
    715: { name: "Deathly Horror", type: "range", role: "attack", food: "food", consumption: 5 },
    716: { name: "Swashbuckler", type: "melee", role: "attack", food: "food", consumption: 0 },
    717: { name: "Sail Ripper", type: "range", role: "attack", food: "food", consumption: 0 },
    718: { name: "Tentacle", type: "melee", role: "attack", food: "food", consumption: 0 },
    719: { name: "Kraken Head", type: "range", role: "attack", food: "food", consumption: 0 },
    720: { name: "Wolfhound", type: "melee", role: "attack", food: "food", consumption: 3 },
    721: { name: "Barbarian", type: "melee", role: "attack", food: "food", consumption: 4 },
    722: { name: "Composite Bowman", type: "range", role: "defense", food: "food", consumption: 3 },
    723: { name: "Flame Bearer", type: "melee", role: "defense", food: "food", consumption: 3 },
    724: { name: "Veteran Swordsman", type: "melee", role: "attack", food: "food", consumption: 6 },
    725: { name: "Khan Guard", type: "melee", role: "attack", food: "food", consumption: 5 },
    726: { name: "Saber Cleaver", type: "melee", role: "attack", food: "food", consumption: 4 },
    727: { name: "Slingshot", type: "range", role: "attack", food: "food", consumption: 4 },
    728: { name: "Renegade Lancer", type: "melee", role: "defense", food: "food", consumption: 3 },
    729: { name: "Renegade Spear Thrower", type: "range", role: "defense", food: "food", consumption: 3 },
    743: { name: "Lancer", type: "melee", role: "defense", food: "food", consumption: 0 },
    744: { name: "Spear Thrower", type: "range", role: "defense", food: "food", consumption: 0 },
    746: { name: "Militia", type: "melee", role: "defense", food: "food", consumption: 0 },
    747: { name: "Shadow Scoundrel", type: "melee", role: "attack", food: "food", consumption: 0 },
    748: { name: "Shadow Wretch", type: "range", role: "attack", food: "food", consumption: 0 },
    749: { name: "Shadow Battering Ram", type: "melee", role: "attack", food: "food", consumption: 0 },
    750: { name: "Shadow Siege Tower", type: "melee", role: "attack", food: "food", consumption: 0 },
    751: { name: "Shadow Assault Bridge", type: "melee", role: "attack", food: "food", consumption: 0 },
    752: { name: "Shadow Mantlet", type: "melee", role: "attack", food: "food", consumption: 0 },
    753: { name: "Demon Slayer", type: "melee", role: "attack", food: "food", consumption: 6 },
    754: { name: "Assassin", type: "range", role: "attack", food: "food", consumption: 6 },
    759: { name: "Renegade Swashbuckler", type: "melee", role: "attack", food: "food", consumption: 6 },
    760: { name: "Renegade Sail Ripper", type: "range", role: "attack", food: "food", consumption: 6 },
    765: { name: "Veteran Marauder", type: "melee", role: "attack", food: "food", consumption: 5 },
    766: { name: "Veteran Pyromaniac", type: "melee", role: "attack", food: "food", consumption: 5 },
    767: { name: "Renegade Shark Tooth Warrior", type: "melee", role: "attack", food: "food", consumption: 4 },
    768: { name: "Renegade Stone Smasher", type: "range", role: "attack", food: "food", consumption: 4 },
    781: { name: "Master Swordsman", type: "melee", role: "attack", food: "food", consumption: 4 },
    782: { name: "Master Archer", type: "range", role: "attack", food: "food", consumption: 4 },
    960: { name: "Forest Warrior", type: "melee", role: "attack", food: "food", consumption: 5 },
    961: { name: "Forest Hunter", type: "range", role: "attack", food: "food", consumption: 5 },
    962: { name: "Renegade Swashbuckler", type: "melee", role: "attack", food: "food", consumption: 6 },
    963: { name: "Renegade Sail Ripper", type: "range", role: "attack", food: "food", consumption: 6 },
    // Leveled units inherit type/role from base unit
    // Shield-Maiden (melee/attack) - MEAD
    196: { name: "Shield-Maiden", type: "melee", role: "attack", food: "mead", consumption: 2 },
    197: { name: "Shield-Maiden", type: "melee", role: "attack", food: "mead", consumption: 2 },
    198: { name: "Shield-Maiden", type: "melee", role: "attack", food: "mead", consumption: 2 },
    199: { name: "Shield-Maiden", type: "melee", role: "attack", food: "mead", consumption: 2 },
    200: { name: "Shield-Maiden", type: "melee", role: "attack", food: "mead", consumption: 2 },
    201: { name: "Shield-Maiden", type: "melee", role: "attack", food: "mead", consumption: 2 },
    202: { name: "Shield-Maiden", type: "melee", role: "attack", food: "mead", consumption: 2 },
    203: { name: "Shield-Maiden", type: "melee", role: "attack", food: "mead", consumption: 2 },
    204: { name: "Shield-Maiden", type: "melee", role: "attack", food: "mead", consumption: 2 },
    215: { name: "Shield-Maiden", type: "melee", role: "attack", food: "mead", consumption: 2 },
    // Valkyrie Ranger (range/attack) - MEAD
    206: { name: "Valkyrie Ranger", type: "range", role: "attack", food: "mead", consumption: 2 },
    207: { name: "Valkyrie Ranger", type: "range", role: "attack", food: "mead", consumption: 2 },
    208: { name: "Valkyrie Ranger", type: "range", role: "attack", food: "mead", consumption: 2 },
    209: { name: "Valkyrie Ranger", type: "range", role: "attack", food: "mead", consumption: 2 },
    210: { name: "Valkyrie Ranger", type: "range", role: "attack", food: "mead", consumption: 2 },
    211: { name: "Valkyrie Ranger", type: "range", role: "attack", food: "mead", consumption: 2 },
    212: { name: "Valkyrie Ranger", type: "range", role: "attack", food: "mead", consumption: 2 },
    213: { name: "Valkyrie Ranger", type: "range", role: "attack", food: "mead", consumption: 2 },
    214: { name: "Valkyrie Ranger", type: "range", role: "attack", food: "mead", consumption: 2 },
    216: { name: "Valkyrie Ranger", type: "range", role: "attack", food: "mead", consumption: 2 },
    // Protector of the North (melee/defense) - MEAD
    218: { name: "Protector of the North", type: "melee", role: "defense", food: "mead", consumption: 2 },
    219: { name: "Protector of the North", type: "melee", role: "defense", food: "mead", consumption: 2 },
    220: { name: "Protector of the North", type: "melee", role: "defense", food: "mead", consumption: 2 },
    221: { name: "Protector of the North", type: "melee", role: "defense", food: "mead", consumption: 2 },
    222: { name: "Protector of the North", type: "melee", role: "defense", food: "mead", consumption: 2 },
    223: { name: "Protector of the North", type: "melee", role: "defense", food: "mead", consumption: 2 },
    224: { name: "Protector of the North", type: "melee", role: "defense", food: "mead", consumption: 2 },
    225: { name: "Protector of the North", type: "melee", role: "defense", food: "mead", consumption: 2 },
    226: { name: "Protector of the North", type: "melee", role: "defense", food: "mead", consumption: 2 },
    227: { name: "Protector of the North", type: "melee", role: "defense", food: "mead", consumption: 2 },
    489: { name: "Protector of the North", type: "melee", role: "defense", food: "mead", consumption: 2 },
    // Valkyrie Sniper (range/defense) - MEAD
    229: { name: "Valkyrie Sniper", type: "range", role: "defense", food: "mead", consumption: 2 },
    230: { name: "Valkyrie Sniper", type: "range", role: "defense", food: "mead", consumption: 2 },
    231: { name: "Valkyrie Sniper", type: "range", role: "defense", food: "mead", consumption: 2 },
    232: { name: "Valkyrie Sniper", type: "range", role: "defense", food: "mead", consumption: 2 },
    233: { name: "Valkyrie Sniper", type: "range", role: "defense", food: "mead", consumption: 2 },
    234: { name: "Valkyrie Sniper", type: "range", role: "defense", food: "mead", consumption: 2 },
    235: { name: "Valkyrie Sniper", type: "range", role: "defense", food: "mead", consumption: 2 },
    236: { name: "Valkyrie Sniper", type: "range", role: "defense", food: "mead", consumption: 2 },
    237: { name: "Valkyrie Sniper", type: "range", role: "defense", food: "mead", consumption: 2 },
    238: { name: "Valkyrie Sniper", type: "range", role: "defense", food: "mead", consumption: 2 },
    493: { name: "Valkyrie Sniper", type: "range", role: "defense", food: "mead", consumption: 2 },
    // Forsaken Maiden - MEAD
    472: { name: "Forsaken Maiden", type: "melee", role: "attack", food: "mead", consumption: 2 },
    483: { name: "Forsaken Maiden", type: "melee", role: "attack", food: "mead", consumption: 2 },
    // Forlorn Ranger - MEAD
    473: { name: "Forlorn Ranger", type: "range", role: "attack", food: "mead", consumption: 2 },
    484: { name: "Forlorn Ranger", type: "range", role: "attack", food: "mead", consumption: 2 },
    // Glasswing Archer (range/attack) - BEEF
    514: { name: "Glasswing Archer", type: "range", role: "attack", food: "beef", consumption: 2 },
    515: { name: "Glasswing Archer", type: "range", role: "attack", food: "beef", consumption: 2 },
    516: { name: "Glasswing Archer", type: "range", role: "attack", food: "beef", consumption: 2 },
    517: { name: "Glasswing Archer", type: "range", role: "attack", food: "beef", consumption: 2 },
    518: { name: "Glasswing Archer", type: "range", role: "attack", food: "beef", consumption: 2 },
    519: { name: "Glasswing Archer", type: "range", role: "attack", food: "beef", consumption: 2 },
    520: { name: "Glasswing Archer", type: "range", role: "attack", food: "beef", consumption: 2 },
    521: { name: "Glasswing Archer", type: "range", role: "attack", food: "beef", consumption: 2 },
    522: { name: "Glasswing Archer", type: "range", role: "attack", food: "beef", consumption: 2 },
    523: { name: "Glasswing Archer", type: "range", role: "attack", food: "beef", consumption: 2 },
    // Flamebreath Berserker (melee/attack) - BEEF
    525: { name: "Flamebreath Berserker", type: "melee", role: "attack", food: "beef", consumption: 2 },
    526: { name: "Flamebreath Berserker", type: "melee", role: "attack", food: "beef", consumption: 2 },
    527: { name: "Flamebreath Berserker", type: "melee", role: "attack", food: "beef", consumption: 2 },
    528: { name: "Flamebreath Berserker", type: "melee", role: "attack", food: "beef", consumption: 2 },
    529: { name: "Flamebreath Berserker", type: "melee", role: "attack", food: "beef", consumption: 2 },
    530: { name: "Flamebreath Berserker", type: "melee", role: "attack", food: "beef", consumption: 2 },
    531: { name: "Flamebreath Berserker", type: "melee", role: "attack", food: "beef", consumption: 2 },
    532: { name: "Flamebreath Berserker", type: "melee", role: "attack", food: "beef", consumption: 2 },
    533: { name: "Flamebreath Berserker", type: "melee", role: "attack", food: "beef", consumption: 2 },
    534: { name: "Flamebreath Berserker", type: "melee", role: "attack", food: "beef", consumption: 2 },
    // Scalebound Guardian (melee/attack) - BEEF
    536: { name: "Scalebound Guardian", type: "melee", role: "attack", food: "beef", consumption: 2 },
    537: { name: "Scalebound Guardian", type: "melee", role: "attack", food: "beef", consumption: 2 },
    538: { name: "Scalebound Guardian", type: "melee", role: "attack", food: "beef", consumption: 2 },
    539: { name: "Scalebound Guardian", type: "melee", role: "attack", food: "beef", consumption: 2 },
    540: { name: "Scalebound Guardian", type: "melee", role: "attack", food: "beef", consumption: 2 },
    541: { name: "Scalebound Guardian", type: "melee", role: "attack", food: "beef", consumption: 2 },
    542: { name: "Scalebound Guardian", type: "melee", role: "attack", food: "beef", consumption: 2 },
    543: { name: "Scalebound Guardian", type: "melee", role: "attack", food: "beef", consumption: 2 },
    544: { name: "Scalebound Guardian", type: "melee", role: "attack", food: "beef", consumption: 2 },
    545: { name: "Scalebound Guardian", type: "melee", role: "attack", food: "beef", consumption: 2 },
    // Scaleshard Marksman (range/attack) - BEEF
    547: { name: "Scaleshard Marksman", type: "range", role: "attack", food: "beef", consumption: 2 },
    548: { name: "Scaleshard Marksman", type: "range", role: "attack", food: "beef", consumption: 2 },
    549: { name: "Scaleshard Marksman", type: "range", role: "attack", food: "beef", consumption: 2 },
    550: { name: "Scaleshard Marksman", type: "range", role: "attack", food: "beef", consumption: 2 },
    551: { name: "Scaleshard Marksman", type: "range", role: "attack", food: "beef", consumption: 2 },
    552: { name: "Scaleshard Marksman", type: "range", role: "attack", food: "beef", consumption: 2 },
    553: { name: "Scaleshard Marksman", type: "range", role: "attack", food: "beef", consumption: 2 },
    554: { name: "Scaleshard Marksman", type: "range", role: "attack", food: "beef", consumption: 2 },
    555: { name: "Scaleshard Marksman", type: "range", role: "attack", food: "beef", consumption: 2 },
    556: { name: "Scaleshard Marksman", type: "range", role: "attack", food: "beef", consumption: 2 },
    // Swashbuckler (melee/attack) - FOOD
    701: { name: "Swashbuckler", type: "melee", role: "attack", food: "food", consumption: 0 },
    702: { name: "Swashbuckler", type: "melee", role: "attack", food: "food", consumption: 0 },
    // Sail Ripper (range/attack) - FOOD
    703: { name: "Sail Ripper", type: "range", role: "attack", food: "food", consumption: 0 },
    704: { name: "Sail Ripper", type: "range", role: "attack", food: "food", consumption: 0 },
    // Renegade Swashbuckler (melee/attack) - FOOD
    705: { name: "Renegade Swashbuckler", type: "melee", role: "attack", food: "food", consumption: 6 },
    706: { name: "Renegade Swashbuckler", type: "melee", role: "attack", food: "food", consumption: 6 },
    // Renegade Sail Ripper (range/attack) - FOOD
    707: { name: "Renegade Sail Ripper", type: "range", role: "attack", food: "food", consumption: 6 },
    708: { name: "Renegade Sail Ripper", type: "range", role: "attack", food: "food", consumption: 6 },
    // Katana Warrior (melee/defense) - FOOD
    820: { name: "Katana Warrior", type: "melee", role: "defense", food: "food", consumption: 0 },
    821: { name: "Katana Warrior", type: "melee", role: "defense", food: "food", consumption: 0 },
    822: { name: "Katana Warrior", type: "melee", role: "defense", food: "food", consumption: 0 },
    823: { name: "Katana Warrior", type: "melee", role: "defense", food: "food", consumption: 0 },
    824: { name: "Katana Warrior", type: "melee", role: "defense", food: "food", consumption: 0 },
    825: { name: "Katana Warrior", type: "melee", role: "defense", food: "food", consumption: 0 },
    826: { name: "Katana Warrior", type: "melee", role: "defense", food: "food", consumption: 0 },
    827: { name: "Katana Warrior", type: "melee", role: "defense", food: "food", consumption: 0 },
    828: { name: "Katana Warrior", type: "melee", role: "defense", food: "food", consumption: 0 },
    829: { name: "Katana Warrior", type: "melee", role: "defense", food: "food", consumption: 0 },
    // Bow Master (range/defense) - FOOD
    830: { name: "Bow Master", type: "range", role: "defense", food: "food", consumption: 3 },
    831: { name: "Bow Master", type: "range", role: "defense", food: "food", consumption: 3 },
    832: { name: "Bow Master", type: "range", role: "defense", food: "food", consumption: 3 },
    833: { name: "Bow Master", type: "range", role: "defense", food: "food", consumption: 3 },
    834: { name: "Bow Master", type: "range", role: "defense", food: "food", consumption: 3 },
    835: { name: "Bow Master", type: "range", role: "defense", food: "food", consumption: 3 },
    836: { name: "Bow Master", type: "range", role: "defense", food: "food", consumption: 3 },
    837: { name: "Bow Master", type: "range", role: "defense", food: "food", consumption: 3 },
    838: { name: "Bow Master", type: "range", role: "defense", food: "food", consumption: 3 },
    839: { name: "Bow Master", type: "range", role: "defense", food: "food", consumption: 3 },
    // Sai Warrior (melee/attack) - FOOD
    861: { name: "Sai Warrior", type: "melee", role: "attack", food: "food", consumption: 0 },
    862: { name: "Sai Warrior", type: "melee", role: "attack", food: "food", consumption: 0 },
    863: { name: "Sai Warrior", type: "melee", role: "attack", food: "food", consumption: 0 },
    864: { name: "Sai Warrior", type: "melee", role: "attack", food: "food", consumption: 0 },
    865: { name: "Sai Warrior", type: "melee", role: "attack", food: "food", consumption: 0 },
    866: { name: "Sai Warrior", type: "melee", role: "attack", food: "food", consumption: 0 },
    867: { name: "Sai Warrior", type: "melee", role: "attack", food: "food", consumption: 0 },
    868: { name: "Sai Warrior", type: "melee", role: "attack", food: "food", consumption: 0 },
    869: { name: "Sai Warrior", type: "melee", role: "attack", food: "food", consumption: 0 },
    // Kunai Thrower (range/attack) - FOOD
    871: { name: "Kunai Thrower", type: "range", role: "attack", food: "food", consumption: 0 },
    872: { name: "Kunai Thrower", type: "range", role: "attack", food: "food", consumption: 0 },
    873: { name: "Kunai Thrower", type: "range", role: "attack", food: "food", consumption: 0 },
    874: { name: "Kunai Thrower", type: "range", role: "attack", food: "food", consumption: 0 },
    875: { name: "Kunai Thrower", type: "range", role: "attack", food: "food", consumption: 0 },
    876: { name: "Kunai Thrower", type: "range", role: "attack", food: "food", consumption: 0 },
    877: { name: "Kunai Thrower", type: "range", role: "attack", food: "food", consumption: 0 },
    878: { name: "Kunai Thrower", type: "range", role: "attack", food: "food", consumption: 0 },
    879: { name: "Kunai Thrower", type: "range", role: "attack", food: "food", consumption: 0 },
    // Lancer (melee/defense) - FOOD
    900: { name: "Lancer", type: "melee", role: "defense", food: "food", consumption: 0 },
    901: { name: "Lancer", type: "melee", role: "defense", food: "food", consumption: 0 },
    902: { name: "Lancer", type: "melee", role: "defense", food: "food", consumption: 0 },
    903: { name: "Lancer", type: "melee", role: "defense", food: "food", consumption: 0 },
    904: { name: "Lancer", type: "melee", role: "defense", food: "food", consumption: 0 },
    905: { name: "Lancer", type: "melee", role: "defense", food: "food", consumption: 0 },
    906: { name: "Lancer", type: "melee", role: "defense", food: "food", consumption: 0 },
    907: { name: "Lancer", type: "melee", role: "defense", food: "food", consumption: 0 },
    908: { name: "Lancer", type: "melee", role: "defense", food: "food", consumption: 0 },
    909: { name: "Lancer", type: "melee", role: "defense", food: "food", consumption: 0 },
    // Spear Thrower (range/defense) - FOOD
    910: { name: "Spear Thrower", type: "range", role: "defense", food: "food", consumption: 0 },
    911: { name: "Spear Thrower", type: "range", role: "defense", food: "food", consumption: 0 },
    912: { name: "Spear Thrower", type: "range", role: "defense", food: "food", consumption: 0 },
    913: { name: "Spear Thrower", type: "range", role: "defense", food: "food", consumption: 0 },
    914: { name: "Spear Thrower", type: "range", role: "defense", food: "food", consumption: 0 },
    915: { name: "Spear Thrower", type: "range", role: "defense", food: "food", consumption: 0 },
    916: { name: "Spear Thrower", type: "range", role: "defense", food: "food", consumption: 0 },
    917: { name: "Spear Thrower", type: "range", role: "defense", food: "food", consumption: 0 },
    918: { name: "Spear Thrower", type: "range", role: "defense", food: "food", consumption: 0 },
    919: { name: "Spear Thrower", type: "range", role: "defense", food: "food", consumption: 0 },
    // Veteran Saber Cleaver (melee/attack) - FOOD
    940: { name: "Veteran Saber Cleaver", type: "melee", role: "attack", food: "food", consumption: 4 },
    941: { name: "Veteran Saber Cleaver", type: "melee", role: "attack", food: "food", consumption: 4 },
    942: { name: "Veteran Saber Cleaver", type: "melee", role: "attack", food: "food", consumption: 4 },
    943: { name: "Veteran Saber Cleaver", type: "melee", role: "attack", food: "food", consumption: 4 },
    944: { name: "Veteran Saber Cleaver", type: "melee", role: "attack", food: "food", consumption: 4 },
    945: { name: "Veteran Saber Cleaver", type: "melee", role: "attack", food: "food", consumption: 4 },
    946: { name: "Veteran Saber Cleaver", type: "melee", role: "attack", food: "food", consumption: 4 },
    947: { name: "Veteran Saber Cleaver", type: "melee", role: "attack", food: "food", consumption: 4 },
    948: { name: "Veteran Saber Cleaver", type: "melee", role: "attack", food: "food", consumption: 4 },
    949: { name: "Veteran Saber Cleaver", type: "melee", role: "attack", food: "food", consumption: 4 },
    // Veteran Slingshot (range/attack) - FOOD
    950: { name: "Veteran Slingshot", type: "range", role: "attack", food: "food", consumption: 4 },
    951: { name: "Veteran Slingshot", type: "range", role: "attack", food: "food", consumption: 4 },
    952: { name: "Veteran Slingshot", type: "range", role: "attack", food: "food", consumption: 4 },
    953: { name: "Veteran Slingshot", type: "range", role: "attack", food: "food", consumption: 4 },
    954: { name: "Veteran Slingshot", type: "range", role: "attack", food: "food", consumption: 4 },
    955: { name: "Veteran Slingshot", type: "range", role: "attack", food: "food", consumption: 4 },
    956: { name: "Veteran Slingshot", type: "range", role: "attack", food: "food", consumption: 4 },
    957: { name: "Veteran Slingshot", type: "range", role: "attack", food: "food", consumption: 4 },
    958: { name: "Veteran Slingshot", type: "range", role: "attack", food: "food", consumption: 4 },
    959: { name: "Veteran Slingshot", type: "range", role: "attack", food: "food", consumption: 4 },
    // Veteran Halberdier (melee/defense) - FOOD
    2000: { name: "Veteran Halberdier", type: "melee", role: "defense", food: "food", consumption: 3 },
    2001: { name: "Veteran Halberdier", type: "melee", role: "defense", food: "food", consumption: 3 },
    2002: { name: "Veteran Halberdier", type: "melee", role: "defense", food: "food", consumption: 3 },
    2003: { name: "Veteran Halberdier", type: "melee", role: "defense", food: "food", consumption: 3 },
    2004: { name: "Veteran Halberdier", type: "melee", role: "defense", food: "food", consumption: 3 },
    2005: { name: "Veteran Halberdier", type: "melee", role: "defense", food: "food", consumption: 3 },
    2006: { name: "Veteran Halberdier", type: "melee", role: "defense", food: "food", consumption: 3 },
    2007: { name: "Veteran Halberdier", type: "melee", role: "defense", food: "food", consumption: 3 },
    2008: { name: "Veteran Halberdier", type: "melee", role: "defense", food: "food", consumption: 3 },
    2009: { name: "Veteran Halberdier", type: "melee", role: "defense", food: "food", consumption: 3 },
    // Veteran Two-Handed Swordsman (melee/attack) - FOOD
    2010: { name: "Veteran Two-Handed Swordsman", type: "melee", role: "attack", food: "food", consumption: 4 },
    2011: { name: "Veteran Two-Handed Swordsman", type: "melee", role: "attack", food: "food", consumption: 4 },
    2012: { name: "Veteran Two-Handed Swordsman", type: "melee", role: "attack", food: "food", consumption: 4 },
    2013: { name: "Veteran Two-Handed Swordsman", type: "melee", role: "attack", food: "food", consumption: 4 },
    2014: { name: "Veteran Two-Handed Swordsman", type: "melee", role: "attack", food: "food", consumption: 4 },
    2015: { name: "Veteran Two-Handed Swordsman", type: "melee", role: "attack", food: "food", consumption: 4 },
    2016: { name: "Veteran Two-Handed Swordsman", type: "melee", role: "attack", food: "food", consumption: 4 },
    2017: { name: "Veteran Two-Handed Swordsman", type: "melee", role: "attack", food: "food", consumption: 4 },
    2018: { name: "Veteran Two-Handed Swordsman", type: "melee", role: "attack", food: "food", consumption: 4 },
    2019: { name: "Veteran Two-Handed Swordsman", type: "melee", role: "attack", food: "food", consumption: 4 },
    // Relic Axeman (melee/attack) - FOOD
    2020: { name: "Relic Axeman", type: "melee", role: "attack", food: "food", consumption: 5 },
    2021: { name: "Relic Axeman", type: "melee", role: "attack", food: "food", consumption: 5 },
    2022: { name: "Relic Axeman", type: "melee", role: "attack", food: "food", consumption: 5 },
    2023: { name: "Relic Axeman", type: "melee", role: "attack", food: "food", consumption: 5 },
    2024: { name: "Relic Axeman", type: "melee", role: "attack", food: "food", consumption: 5 },
    2025: { name: "Relic Axeman", type: "melee", role: "attack", food: "food", consumption: 5 },
    2026: { name: "Relic Axeman", type: "melee", role: "attack", food: "food", consumption: 5 },
    2027: { name: "Relic Axeman", type: "melee", role: "attack", food: "food", consumption: 5 },
    2028: { name: "Relic Axeman", type: "melee", role: "attack", food: "food", consumption: 5 },
    2029: { name: "Relic Axeman", type: "melee", role: "attack", food: "food", consumption: 5 },
    // Relic Hammerman (melee/defense) - FOOD
    2030: { name: "Relic Hammerman", type: "melee", role: "defense", food: "food", consumption: 4 },
    2031: { name: "Relic Hammerman", type: "melee", role: "defense", food: "food", consumption: 4 },
    2032: { name: "Relic Hammerman", type: "melee", role: "defense", food: "food", consumption: 4 },
    2033: { name: "Relic Hammerman", type: "melee", role: "defense", food: "food", consumption: 4 },
    2034: { name: "Relic Hammerman", type: "melee", role: "defense", food: "food", consumption: 4 },
    2035: { name: "Relic Hammerman", type: "melee", role: "defense", food: "food", consumption: 4 },
    2036: { name: "Relic Hammerman", type: "melee", role: "defense", food: "food", consumption: 4 },
    2037: { name: "Relic Hammerman", type: "melee", role: "defense", food: "food", consumption: 4 },
    2038: { name: "Relic Hammerman", type: "melee", role: "defense", food: "food", consumption: 4 },
    2039: { name: "Relic Hammerman", type: "melee", role: "defense", food: "food", consumption: 4 },
    // Veteran Longbowman (range/defense) - FOOD
    2040: { name: "Veteran Longbowman", type: "range", role: "defense", food: "food", consumption: 3 },
    2041: { name: "Veteran Longbowman", type: "range", role: "defense", food: "food", consumption: 3 },
    2042: { name: "Veteran Longbowman", type: "range", role: "defense", food: "food", consumption: 3 },
    2043: { name: "Veteran Longbowman", type: "range", role: "defense", food: "food", consumption: 3 },
    2044: { name: "Veteran Longbowman", type: "range", role: "defense", food: "food", consumption: 3 },
    2045: { name: "Veteran Longbowman", type: "range", role: "defense", food: "food", consumption: 3 },
    2046: { name: "Veteran Longbowman", type: "range", role: "defense", food: "food", consumption: 3 },
    2047: { name: "Veteran Longbowman", type: "range", role: "defense", food: "food", consumption: 3 },
    2048: { name: "Veteran Longbowman", type: "range", role: "defense", food: "food", consumption: 3 },
    2049: { name: "Veteran Longbowman", type: "range", role: "defense", food: "food", consumption: 3 },
    // Veteran Heavy Crossbowman (range/attack) - FOOD
    2050: { name: "Veteran Heavy Crossbowman", type: "range", role: "attack", food: "food", consumption: 4 },
    2051: { name: "Veteran Heavy Crossbowman", type: "range", role: "attack", food: "food", consumption: 4 },
    2052: { name: "Veteran Heavy Crossbowman", type: "range", role: "attack", food: "food", consumption: 4 },
    2053: { name: "Veteran Heavy Crossbowman", type: "range", role: "attack", food: "food", consumption: 4 },
    2054: { name: "Veteran Heavy Crossbowman", type: "range", role: "attack", food: "food", consumption: 4 },
    2055: { name: "Veteran Heavy Crossbowman", type: "range", role: "attack", food: "food", consumption: 4 },
    2056: { name: "Veteran Heavy Crossbowman", type: "range", role: "attack", food: "food", consumption: 4 },
    2057: { name: "Veteran Heavy Crossbowman", type: "range", role: "attack", food: "food", consumption: 4 },
    2058: { name: "Veteran Heavy Crossbowman", type: "range", role: "attack", food: "food", consumption: 4 },
    2059: { name: "Veteran Heavy Crossbowman", type: "range", role: "attack", food: "food", consumption: 4 },
    // Relic Shortbowman (range/attack) - FOOD
    2060: { name: "Relic Shortbowman", type: "range", role: "attack", food: "food", consumption: 5 },
    2061: { name: "Relic Shortbowman", type: "range", role: "attack", food: "food", consumption: 5 },
    2062: { name: "Relic Shortbowman", type: "range", role: "attack", food: "food", consumption: 5 },
    2063: { name: "Relic Shortbowman", type: "range", role: "attack", food: "food", consumption: 5 },
    2064: { name: "Relic Shortbowman", type: "range", role: "attack", food: "food", consumption: 5 },
    2065: { name: "Relic Shortbowman", type: "range", role: "attack", food: "food", consumption: 5 },
    2066: { name: "Relic Shortbowman", type: "range", role: "attack", food: "food", consumption: 5 },
    2067: { name: "Relic Shortbowman", type: "range", role: "attack", food: "food", consumption: 5 },
    2068: { name: "Relic Shortbowman", type: "range", role: "attack", food: "food", consumption: 5 },
    2069: { name: "Relic Shortbowman", type: "range", role: "attack", food: "food", consumption: 5 },
    // Relic Longbowman (range/defense) - FOOD
    2070: { name: "Relic Longbowman", type: "range", role: "defense", food: "food", consumption: 4 },
    2071: { name: "Relic Longbowman", type: "range", role: "defense", food: "food", consumption: 4 },
    2072: { name: "Relic Longbowman", type: "range", role: "defense", food: "food", consumption: 4 },
    2073: { name: "Relic Longbowman", type: "range", role: "defense", food: "food", consumption: 4 },
    2074: { name: "Relic Longbowman", type: "range", role: "defense", food: "food", consumption: 4 },
    2075: { name: "Relic Longbowman", type: "range", role: "defense", food: "food", consumption: 4 },
    2076: { name: "Relic Longbowman", type: "range", role: "defense", food: "food", consumption: 4 },
    2077: { name: "Relic Longbowman", type: "range", role: "defense", food: "food", consumption: 4 },
    2078: { name: "Relic Longbowman", type: "range", role: "defense", food: "food", consumption: 4 },
    2079: { name: "Relic Longbowman", type: "range", role: "defense", food: "food", consumption: 4 },
};

// ============================================
// TOOL_METADATA
// ============================================
export const TOOL_METADATA: Record<number, UnitMeta> = {
};

// ============================================
// UNIT_LEVEL_MAP - baseUnitId -> level -> actualUnitId
// ============================================
export const UNIT_LEVEL_MAP: Record<number, Record<number, number>> = {
    // Shield-Maiden
    195: {
        1: 196,
        2: 197,
        3: 198,
        4: 199,
        5: 200,
        6: 201,
        7: 202,
        8: 203,
        9: 204,
        10: 215,
    },
    // Valkyrie Ranger
    205: {
        1: 206,
        2: 207,
        3: 208,
        4: 209,
        5: 210,
        6: 211,
        7: 212,
        8: 213,
        9: 214,
        10: 216,
    },
    // Protector of the North
    217: {
        1: 218,
        2: 219,
        3: 220,
        4: 221,
        5: 222,
        6: 223,
        7: 224,
        8: 225,
        9: 226,
        10: 227,
        11: 489,
    },
    // Valkyrie Sniper
    228: {
        1: 229,
        2: 230,
        3: 231,
        4: 232,
        5: 233,
        6: 234,
        7: 235,
        8: 236,
        9: 237,
        10: 238,
        11: 493,
    },
    // Forsaken Maiden
    502: {
        1: 502,
        10: 472,
    },
    // Forlorn Ranger
    503: {
        1: 503,
        10: 473,
    },
    // Glasswing Archer
    513: {
        1: 514,
        2: 515,
        3: 516,
        4: 517,
        5: 518,
        6: 519,
        7: 520,
        8: 521,
        9: 522,
        10: 523,
    },
    // Flamebreath Berserker
    524: {
        1: 525,
        2: 526,
        3: 527,
        4: 528,
        5: 529,
        6: 530,
        7: 531,
        8: 532,
        9: 533,
        10: 534,
    },
    // Scalebound Guardian
    535: {
        1: 536,
        2: 537,
        3: 538,
        4: 539,
        5: 540,
        6: 541,
        7: 542,
        8: 543,
        9: 544,
        10: 545,
    },
    // Scaleshard Marksman
    546: {
        1: 547,
        2: 548,
        3: 549,
        4: 550,
        5: 551,
        6: 552,
        7: 553,
        8: 554,
        9: 555,
        10: 556,
    },
    // Swashbuckler
    716: {
        1: 701,
        2: 702,
    },
    // Sail Ripper
    717: {
        1: 703,
        2: 704,
    },
    // Renegade Swashbuckler
    759: {
        1: 705,
        2: 706,
    },
    // Renegade Sail Ripper
    760: {
        1: 707,
        2: 708,
    },
    // Katana Warrior
    38: {
        1: 820,
        2: 821,
        3: 822,
        4: 823,
        5: 824,
        6: 825,
        7: 826,
        8: 827,
        9: 828,
        10: 829,
    },
    // Bow Master
    39: {
        1: 830,
        2: 831,
        3: 832,
        4: 833,
        5: 834,
        6: 835,
        7: 836,
        8: 837,
        9: 838,
        10: 839,
    },
    // Sai Warrior
    860: {
        1: 860,
        2: 861,
        3: 862,
        4: 863,
        5: 864,
        6: 865,
        7: 866,
        8: 867,
        9: 868,
        10: 869,
    },
    // Kunai Thrower
    870: {
        1: 870,
        2: 871,
        3: 872,
        4: 873,
        5: 874,
        6: 875,
        7: 876,
        8: 877,
        9: 878,
        10: 879,
    },
    // Lancer
    743: {
        1: 900,
        2: 901,
        3: 902,
        4: 903,
        5: 904,
        6: 905,
        7: 906,
        8: 907,
        9: 908,
        10: 909,
    },
    // Spear Thrower
    744: {
        1: 910,
        2: 911,
        3: 912,
        4: 913,
        5: 914,
        6: 915,
        7: 916,
        8: 917,
        9: 918,
        10: 919,
    },
    // Veteran Saber Cleaver
    5: {
        1: 940,
        2: 941,
        3: 942,
        4: 943,
        5: 944,
        6: 945,
        7: 946,
        8: 947,
        9: 948,
        10: 949,
    },
    // Veteran Slingshot
    6: {
        1: 950,
        2: 951,
        3: 952,
        4: 953,
        5: 954,
        6: 955,
        7: 956,
        8: 957,
        9: 958,
        10: 959,
    },
    // Veteran Halberdier
    308: {
        1: 2000,
        2: 2001,
        3: 2002,
        4: 2003,
        5: 2004,
        6: 2005,
        7: 2006,
        8: 2007,
        9: 2008,
        10: 2009,
    },
    // Veteran Two-Handed Swordsman
    309: {
        1: 2010,
        2: 2011,
        3: 2012,
        4: 2013,
        5: 2014,
        6: 2015,
        7: 2016,
        8: 2017,
        9: 2018,
        10: 2019,
    },
    // Relic Axeman
    148: {
        1: 2020,
        2: 2021,
        3: 2022,
        4: 2023,
        5: 2024,
        6: 2025,
        7: 2026,
        8: 2027,
        9: 2028,
        10: 2029,
    },
    // Relic Hammerman
    150: {
        1: 2030,
        2: 2031,
        3: 2032,
        4: 2033,
        5: 2034,
        6: 2035,
        7: 2036,
        8: 2037,
        9: 2038,
        10: 2039,
    },
    // Veteran Longbowman
    311: {
        1: 2040,
        2: 2041,
        3: 2042,
        4: 2043,
        5: 2044,
        6: 2045,
        7: 2046,
        8: 2047,
        9: 2048,
        10: 2049,
    },
    // Veteran Heavy Crossbowman
    312: {
        1: 2050,
        2: 2051,
        3: 2052,
        4: 2053,
        5: 2054,
        6: 2055,
        7: 2056,
        8: 2057,
        9: 2058,
        10: 2059,
    },
    // Relic Shortbowman
    149: {
        1: 2060,
        2: 2061,
        3: 2062,
        4: 2063,
        5: 2064,
        6: 2065,
        7: 2066,
        8: 2067,
        9: 2068,
        10: 2069,
    },
    // Relic Longbowman
    151: {
        1: 2070,
        2: 2071,
        3: 2072,
        4: 2073,
        5: 2074,
        6: 2075,
        7: 2076,
        8: 2077,
        9: 2078,
        10: 2079,
    },
};

// ============================================
// Reverse Lookup: unitId -> { baseId, level }
// ============================================
export const UNIT_TO_BASE_MAP: Record<number, { baseId: number; level: number }> = {};

// Populate UNIT_TO_BASE_MAP from UNIT_LEVEL_MAP
Object.entries(UNIT_LEVEL_MAP).forEach(([baseIdStr, levels]) => {
    const baseId = parseInt(baseIdStr);
    Object.entries(levels).forEach(([levelStr, unitId]) => {
        const level = parseInt(levelStr);
        UNIT_TO_BASE_MAP[unitId] = { baseId, level };
    });
});

/**
 * Get the base unit ID and level for a given unit ID.
 * If the unit is not in the level map, returns null.
 */
export function getUnitBaseAndLevel(unitId: number): { baseId: number; level: number } | null {
    return UNIT_TO_BASE_MAP[unitId] || null;
}

/**
 * Get the actual unit ID for a base unit at a specific level.
 * If not found, returns the baseId itself.
 */
export function getUnitIdForLevel(baseId: number, level: number): number {
    return UNIT_LEVEL_MAP[baseId]?.[level] ?? baseId;
}