import type {MessageKey} from '../i18n/messages';
/**
 * In-app changelog. Append a new release at the top when you ship a version.
 */
export const PATCH_NOTE_KIND_ORDER = [
  'added',
  'fixed',
  'security',
  'changed',
  'removed',
  'deprecated',
] as const;

export type PatchNoteKind = (typeof PATCH_NOTE_KIND_ORDER)[number];

export interface PatchNoteItem {
  kind: PatchNoteKind;
  text: string;
  textKey: MessageKey;
}

/** Badge label shown in the UI for each kind */
export const PATCH_NOTE_KIND_LABEL: Record<PatchNoteKind, string> = {
  added: 'Added',
  fixed: 'Fixed',
  security: 'Security',
  changed: 'Changed',
  removed: 'Removed',
  deprecated: 'Deprecated',
};

export interface PatchNotesRelease {
  version: string;
  /** Short subtitle for the release card */
  subtitle?: string;
  subtitleKey?: MessageKey;
  /** Optional ISO date string for display */
  date?: string;
  /** Changelog lines, each tagged for badge + color */
  items: PatchNoteItem[];
}

const PATCH_NOTE_KIND_RANK = PATCH_NOTE_KIND_ORDER.reduce<Record<PatchNoteKind, number>>(
  (rank, kind, index) => {
    rank[kind] = index;
    return rank;
  },
  {} as Record<PatchNoteKind, number>,
);

export function sortPatchNoteItems(items: readonly PatchNoteItem[]): PatchNoteItem[] {
  return items
    .map((item, index) => ({ item, index }))
    .sort((left, right) => (
      PATCH_NOTE_KIND_RANK[left.item.kind] - PATCH_NOTE_KIND_RANK[right.item.kind]
      || left.index - right.index
    ))
    .map(({ item }) => item);
}

const PATCH_NOTES_RELEASES_UNSORTED: PatchNotesRelease[] = [
  {
    version: '2.4.0',
    subtitleKey: "patchNotes.release.2.4.0.subtitle.fd3fec582d3e",
        subtitle: 'Fortress automation, castle controls, and clearer equipment choices',
    date: '2026-09-20',
    items: [
      { kind: 'added', textKey: "patchNotes.release.2.4.0.text.6d8d975de029",
        text: "Auto Fortress attacks freshly available outer-kingdom fortresses within saved limits, distributes purchased Direwolves across enabled castles, and can use guarded Time Skips for its own confirmed transfers." },
      { kind: 'added', textKey: "patchNotes.release.2.4.0.text.c34be0e3c35b",
        text: "Auto Booster optionally buys the daily fortress-speed offer while preserving your saved ruby reserve and confirming the active effect." },
      { kind: 'added', textKey: "patchNotes.release.2.4.0.text.821a2a794670",
        text: "Auto Towers supports Robber Baron Advisor chains, optional activation with a dedicated token, and saved daily Time Skip limits." },
      { kind: 'added', textKey: "patchNotes.release.2.4.0.text.85f108bc673b",
        text: "Auto Bird adds per-castle pause, timed pause and resend controls, runtime preset selection and scheduled preset changes. Enabled Fortress castles keep their reserved Direwolves at home." },
      { kind: 'added', textKey: "patchNotes.release.2.4.0.text.1e9f1701adb1",
        text: "Feature Stats shows final known scores from completed collected events, with dates, ranks and filtering. Unknown scores stay unknown; account scores are not presented as points earned by automation." },
      { kind: 'fixed', textKey: "patchNotes.release.2.4.0.text.2898306c3f8c",
        text: "Auto Bird resumes reliably after support troops return and handles larger troop mixes; premium commander movements no longer stall Auto Towers." },
      { kind: 'fixed', textKey: "patchNotes.release.2.4.0.text.c11dabbde6ff",
        text: "Auto Khan keeps retaliation movements and results visible, follows current camp and rage state, and avoids interference from unrelated support movements." },
      { kind: 'fixed', textKey: "patchNotes.release.2.4.0.text.fb1297c7fe3c",
        text: "Auto Buyer and Khan purchases use the current offer and intended castle. Buyer keeps valid feast and specialist goals working independently, respects reserves, and checks uncertain purchases before trying again." },
      { kind: 'fixed', textKey: "patchNotes.release.2.4.0.text.c7a4c70dd373",
        text: "Food deliveries use the correct marketplace castle, and returning trade carts remain reserved until they arrive home." },
      { kind: 'fixed', textKey: "patchNotes.release.2.4.0.text.9f3b4cebf22f",
        text: "Nomad cooldown skips use fresh cooldown information, and sequential attacks preserve their intended arrival order." },
      { kind: 'fixed', textKey: "patchNotes.release.2.4.0.text.69f11e614567",
        text: "Auto TCI respects attached construction items even when their timers reach zero, and waits when slot information is stale or incomplete." },
      { kind: 'fixed', textKey: "patchNotes.release.2.4.0.text.babafa16b03d",
        text: "Coin spending waits until the latest confirmed balance covers the full command cost, saved reserve and other pending spending." },
      { kind: 'fixed', textKey: "patchNotes.release.2.4.0.text.d079729e2222",
        text: "Hosted settings preserve in-progress drafts and preset save baselines through background updates; invalid drafts cannot start an action." },
      { kind: 'changed', textKey: "patchNotes.release.2.4.0.text.6bb2fa7d84ae",
        text: "Equipment Reconfigure compares up to 10 useful distinct alternatives with complete capped totals and compatible equipment, heroes and gems. Apply uses the selected extraction costs and maximum ruby charge you accepted." },
      { kind: 'changed', textKey: "patchNotes.release.2.4.0.text.e514f9a16bc6",
        text: "Storm and Berimond builders follow ordered construction phases. A blocked phase does not spend on later construction, and Storm warns when required stored decorations are missing." },
      { kind: 'changed', textKey: "patchNotes.release.2.4.0.text.965e5361365e",
        text: "Automation safety pauses expire 30 minutes after the original rejection, including across restarts. Supported duplicate alliance-help responses no longer create unnecessary pauses." },
    ],
  },
  {
    version: '2.3.6',
    subtitleKey: "patchNotes.release.2.3.6.subtitle.5681b3801d43",
        subtitle: 'Reliable event attacks, Storm logistics, and feast upkeep',
    date: '2026-09-10',
    items: [
      { kind: 'fixed', textKey: "patchNotes.release.2.3.6.text.ffeff6e37f1c",
        text: 'Auto Nomad and Samurai now apply saved cooldown skips before every later chained attack, preserve configured Time Skip reserves, recheck the daily limit for each launch, and retain every confirmed launch in attack-rate counts even if a later chain step fails' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.6.text.19ad00fe4c8d",
        text: 'Attack failures now identify incompatible preset tools consistently, and Auto Nomad and Samurai validate official target and event restrictions before sending an attack' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.6.text.01532884f11b",
        text: 'Equipment upgrades now use the correct ordinary or relic command, enforce official item-level caps, and retry consumed failed enchantment rolls after rechecking reserves without counting false level progress' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.6.text.15e57a11aeba",
        text: 'Auto Storm now calculates its troop-import cap from a 5,000-troop baseline, confirmed attacks since reset, average enabled-preset demand, and the configured castle reserve, while the final attack rechecks that the reserve will remain stationed' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.6.text.715f962ad55c",
        text: 'Auto Buyer now makes its master run state visible in feast settings, preserves valid feast timers across partial refreshes, rechecks the current discount and paying-castle balance immediately before purchase, and reconciles uncertain outcomes without repeating a possible spend' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.6.text.7c42e20eb1c5",
        text: 'Auto Buyer now limits automatic feast purchases to protocol-supported food feasts, clearly marks unsupported choices, and requires the refreshed game state to confirm the expected feast and duration after purchase' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.6.text.173a99893cc6",
        text: 'Auto Invasion now assigns one commander per distinct target, rotates past castles with inbound or outbound movements, reservations, protection, or cooldowns, and durably reconciles exact launches and battle reports without duplicate attacks' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.6.text.653a70c6a325",
        text: 'Telemetry retention now removes expired rotated logs from retired or previously unknown feature channels as well as current channels' },
      { kind: 'security', textKey: "patchNotes.release.2.3.6.text.6e3749f15036",
        text: 'Automation now locks the originating lane on unapproved game opcode errors before retrying or continuing a chain. Locks retain the triggering operation across profile restarts and require explicit review; only ADI 95, ERE/EQE 227, and BUP 87 retain existing recovery behavior, while MSD rejections retain a 30-minute cooldown' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.6.text.b1561282170d",
        text: 'Every binary switch now uses the same accessible green-on and red-off styling across pages, settings, modals, pickers, schedulers, equipment, and defense presets' },
    ],
  },
  {
    version: '2.3.5',
    subtitleKey: "patchNotes.release.2.3.5.subtitle.fafdd0d8a2a6",
        subtitle: 'Reliable recruiting and complete Storm history',
    date: '2026-09-02',
    items: [
      { kind: 'fixed', textKey: "patchNotes.release.2.3.5.text.4b172191c232",
        text: 'Auto Recruit now resolves simultaneously displayed Glory prefix and suffix titles through their official ancestry, restoring the enabled level-10 fallback after reconnects while rejecting unrelated title conflicts' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.5.text.1f7981466f11",
        text: 'Recruitment now sends one alliance-help request after every newly committed BUP batch and retries after a castle refresh for the first full-queue slot where the game still reports RAH=false' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.5.text.e4419b67627e",
        text: 'Storm collection now discovers players from the complete Might map by their Storm-realm castle, preserves every readable participation and cargo state before filtering, derives displayed ranks from cargo points, and retains only the last participating scores from the previous calendar month' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.5.text.025370afedfa",
        text: 'Hosted My Stats and Feature Stats now always read their account-scoped retained cloud series while desktop keeps profile-owned disk history; both views open on the full 30-day retention window, and every migrated report category remains selectable after its event ends' },
    ],
  },
  {
    version: '2.3.4',
    subtitleKey: "patchNotes.release.2.3.4.subtitle.01f51b0d964a",
        subtitle: 'Hosted stats recovery and session-safe automation',
    date: '2026-09-01',
    items: [
      { kind: 'added', textKey: "patchNotes.release.2.3.4.text.b55d51fe646c",
        text: 'World Intelligence player dossiers now show one final known score for each completed time-limited event run in a Previous scores section, dated by when the event ended in the viewer\'s local time' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.4.text.ddd09e63b8f1",
        text: 'Storm Islands now admits only players the game marks as participating in the active run, keeps cargo observations rankless in storage, and derives display order from current-session scores so prior-season cargo cannot reappear' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.4.text.f6690669fc34",
        text: 'Mobile World Intelligence search selectors now keep their focus while the software keyboard changes the viewport, so event, date, and player choices remain editable' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.4.text.96d1282d5c0d",
        text: 'Auto Recruit keeps per-castle settings and schedules attached to the current Storm castle after a seasonal castle ID change, applies Glory-title fallback across the selected unit family, and still revalidates exact live recruitability before enqueueing' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.4.text.accc316dd180",
        text: 'Recruitment and hospital alliance-help request lifecycles now survive castle-focus changes and zero-reduction compact queue updates, preventing duplicate requests while requiring current-session same-castle or same-job evidence' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.4.text.1190652163ec",
        text: 'Feature Stats now records every positive parsed report resource into additive UTC-minute buckets keyed by view, then preserves every per-resource total while hosted retention merges older minutes into hourly and daily rows instead of truncating high-volume report history' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.4.text.7175ec82e91a",
        text: 'Hosted tenants now backfill every exact feature report still recoverable from their persistent profile database into the new minute format, merge legacy UID and stable world/player history before account-scoped delivery, publish bounded acknowledgement-backed batches, and report migration coverage before a worker rollout can advance' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.4.text.854560a1abd8",
        text: 'My Stats now keeps every historically nonzero resource and currency selectable after its live balance reaches zero; desktop applies the selected cadence and day limit to its local profile files and cannot initialize hosted private-metrics publishing' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.4.text.607d5e817e3b",
        text: 'The public landing page now loads privacy-bounded ruby loot and completed-attack totals from fresh current hosted accounts instead of waiting on a missing activity endpoint' },
      { kind: 'security', textKey: "patchNotes.release.2.3.4.text.5d69efd7c161",
        text: 'Portal sign-out now revokes the server session with the supported method, expires the scoped HttpOnly cookie, verifies that it can no longer authenticate, and refuses to present a successful logout when revocation cannot be confirmed' },
    ],
  },
  {
    version: '2.3.3',
    subtitleKey: "patchNotes.release.2.3.3.subtitle.dc0004ed135b",
        subtitle: 'Complete Storm intelligence and flexible local history',
    date: '2026-08-31',
    items: [
      { kind: 'added', textKey: "patchNotes.release.2.3.3.text.ae4677a56ca3",
        text: 'My Stats Storage now offers 1, 5, 10, 15, 30, or 60 minute recording intervals, any local whole-number day limit, quick choices including 100 and 365 days, unlimited local retention, and a live estimate of recording count and SQLite storage use' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.3.text.5ed1a667d209",
        text: 'World Intelligence now subscribes through the correct local desktop or hosted-account runtime URL, preventing the client crash caused by the missing HTTP URL helper' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.3.text.3d1b556216eb",
        text: 'Storm Islands collection now keeps every participating player with authoritative cargo metrics even when the game omits or contradicts rank and session metadata; cloud storage merges metrics independently across collectors and derives display order from cargo points' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.3.text.5409dc52a8e1",
        text: 'Current and dated Storm boards now load up to 5,000 participants, collapse legacy false league rows, update live without losing successful data to a stale request, and retain or clamp pagination correctly as rows refresh' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.3.text.ef5bfabe0acc",
        text: 'Failed actions now surface concise user-facing reasons and stable notifications instead of internal response-code or transport wording, while account switches keep operation results scoped to the runtime that submitted them' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.3.text.d451bf913906",
        text: 'Feature switches now use a red off state and green on state while ordinary non-feature switches retain their neutral styling' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.3.text.0ad294cebf67",
        text: 'Local My Stats history keeps the chosen recording cadence throughout the complete retention window, safely compacts when moving to a slower cadence, and resamples chart responses without deleting saved detail; hosted history remains capped at 30 days' },
      { kind: 'removed', textKey: "patchNotes.release.2.3.3.text.85852b2e1631",
        text: 'Experimental Battle Research was removed from Settings and is no longer started by desktop or hosted runtimes; existing local trial records remain untouched' },
    ],
  },
  {
    version: '2.3.2',
    subtitleKey: "patchNotes.release.2.3.2.subtitle.393c3c3dde6d",
        subtitle: 'Account controls, Khan recovery, and verified releases',
    date: '2026-08-29',
    items: [
      { kind: 'added', textKey: "patchNotes.release.2.3.2.text.771f41afdb68",
        text: 'Auto Khan can stop camp attacks after a per-event number of accepted rage retaliations while continuing its full-rage taunt chain, and can optionally require the authoritative timed Rage points booster before another camp attack' },
      { kind: 'added', textKey: "patchNotes.release.2.3.2.text.439a2be9c07f",
        text: 'My Stats Storage now lets local profiles keep no history, 24 hours, 7 days, 30 days, 90 days, one year, or unlimited history; hosted runtimes expose the same control with their existing 30-day storage cap enforced' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.2.text.147f54b8f4d9",
        text: 'Auto Khan now scopes its full-rage taunt cursor to the active Nomad occurrence, waits for an accepted movement response before consuming that rage fill, declares defense-tool purchases with the typed castle inventory resource, and keeps attack-only booster and chain limits from blocking cooldown or defense recovery' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.2.text.eb57f7104ae4",
        text: 'Auto Khan now treats sub-second movement projection jitter as simultaneous at the game wire\'s one-second precision, waits only the attack lane when a newly available faster commander could materially overtake an in-flight hit, and automatically recovers after the relevant arrival' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.2.text.c2853ad7578e",
        text: 'Hospital and recruitment alliance-help requests now wait for the current session\'s authoritative own-help list; hospital allows at most one outstanding request while recruitment continues to cover the castle-wide active queue snapshot' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.2.text.5cf2b2a5f9a8",
        text: 'Attack and defense presets now create and save with section-scoped conflict protection, preserve unrecognized sibling data, and keep troop and tool editors available when unrelated optional catalogs are temporarily unavailable' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.2.text.6ea98f1c8927",
        text: 'Hosted schedules, automation settings, presets, optimizer priorities, Storm or Berimond blueprints, and saved Rift replay templates now belong to the account control plane and remain editable with no runtime; save dialogs wait for durable acknowledgement and workers apply the exact fenced revision before login or automation can resume' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.2.text.a648b1fb2820",
        text: 'Windows component-state persistence no longer attempts an unsupported directory flush that could report Access is denied; state files and recovery directories use write-through Windows moves instead' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.2.text.0fe844564fc0",
        text: 'World Intelligence once again leads Storm Islands with its authoritative cargo ranking instead of presenting page-local session ranks as though every player held the same global place' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.2.text.e770642fba0f",
        text: 'Current and recorded event boards now stay under one event choice, with the event-date picker retaining every returned run and dated Storm boards rebuilding inconsistent ranks from their final recorded scores' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.2.text.783c1089b614",
        text: 'Offense automation daily badges now count confirmed launches from the authoritative server reset boundary instead of a rolling 24-hour window, with the boundary and retained feature telemetry restored after restart' },
      { kind: 'security', textKey: "patchNotes.release.2.3.2.text.730789a10348",
        text: 'Desktop updates now require an exact SHA-256 match and remain restricted to the official release location; unexpected redirects, paths, filenames, missing checksums, and altered downloads are rejected' },
      { kind: 'security', textKey: "patchNotes.release.2.3.2.text.f5eac2dead3b",
        text: 'Automatic updates now require the version service to return the platform artifact URL and SHA-256 directly; public source no longer embeds the provider storage origin or private release-manifest layout' },
      { kind: 'security', textKey: "patchNotes.release.2.3.2.text.ec8a15dfa3d9",
        text: 'The public source tree excludes local report data, environment-specific files, provider-specific build configuration, and production rollout controls; release validation consumes an exact reviewed source revision outside this repository' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.2.text.a9cf0ffca0de",
        text: 'Release output is now limited to the Windows desktop executable and the hosted tenant image; other desktop platform artifacts are no longer built or published' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.2.text.cd75dc59c06f",
        text: 'Auto Beri Builder configuration now remains in Auto Beri settings while the Automation overview presents its runtime status without a second quick toggle' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.2.text.d8014fe5cab6",
        text: 'The dashboard now uses a kingdom-inspired light and dark color palette without changing its layout or spacing' },
    ],
  },
  {
    version: '2.3.1',
    subtitleKey: "patchNotes.release.2.3.1.subtitle.ccc183ded7df",
        subtitle: 'Persistent automation and unified release safety',
    date: '2026-08-25',
    items: [
      { kind: 'added', textKey: "patchNotes.release.2.3.1.text.ad636bacda4f",
        text: 'Auto Beri World now exposes its saved Builder lane toggle beside live lane status, allowing camp construction to stay off while transfers, tools, and tower attacks continue' },
      { kind: 'added', textKey: "patchNotes.release.2.3.1.text.69d50ca564de",
        text: 'Auto Beri World now supports a saved daily attack-count limit using the authoritative account-wide server counter, with an immediate launch-time recheck and automatic resumption after the daily reset' },
      { kind: 'added', textKey: "patchNotes.release.2.3.1.text.0bd6f3a17037",
        text: 'Every offense automation now shows its own confirmed rolling 24-hour launch count beside the existing rolling hourly attack badge, with both windows restored from persistent feature telemetry after restart' },
      { kind: 'added', textKey: "patchNotes.release.2.3.1.text.8dcc33f255c2",
        text: 'Attack presets now offer an optional whole-family troop mode that fills each requested allocation from the highest owned official tier downward, retaining partial higher-tier quantities before using lower tiers' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.1.text.a122d3a41777",
        text: 'Automatic equipment cleanup now runs on the backend scheduler with its interval stored in shared configuration, so cleanup remains active when the desktop or hosted dashboard is closed' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.1.text.e0708ac47a65",
        text: 'Auto Beri Builder now protects every Stable from its demolition candidate list while continuing to reconcile and remove other eligible extra buildings' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.1.text.eef14a4d4000",
        text: 'Live Activity is now a combined user-only stream with official names instead of item, castle, commander, and other internal identifiers; raw game frames remain private backend diagnostics rather than user-visible log details' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.1.text.031d9b512653",
        text: 'Desktop binaries and the hosted ARM64 worker image now come from one source revision and pass guarded 60-second candidate and live-runtime stability gates before release pointers are promoted' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.1.text.f3a9b066efe7",
        text: 'Hosted tenant runtimes now keep persisted state, history, catalogs, and configuration available through game disconnects; every table request carries its tenant-shard session, settings save directly to the durable store without a game action, and configuration-only changes publish a fresh dashboard checkpoint' },
    ],
  },
  {
    version: '2.3.0',
    subtitleKey: "patchNotes.release.2.3.0.subtitle.a04e9d9aa6bf",
        subtitle: 'Dynamic hosted runtimes and sparse revisioned state',
    date: '2026-08-21',
    items: [
      { kind: 'added', textKey: "patchNotes.release.2.3.0.text.bebb45dace3b",
        text: 'The same binary now keeps the ordinary desktop as its zero-configuration one-account composition while an explicit hosted mode can add or drain bounded Background account runtimes live without restarting or interrupting sibling runtimes' },
      { kind: 'added', textKey: "patchNotes.release.2.3.0.text.dda94038e451",
        text: 'Hosted worker cells expose a private idempotent reconciliation and status stream for desired revisions, placement epochs, credential leases and their active or lapsed state, runtime capacity, and sanitized per-runtime readiness' },
      { kind: 'added', textKey: "patchNotes.release.2.3.0.text.695a40948411",
        text: 'Hosted runtimes publish dashboard checkpoints — the exact client state document the dashboard renders, the configuration snapshot, the last hundred operation receipts, and the sanitized session situation — every five minutes while the state changes, promptly after a session transition, and once more before the runtime is drained, so the frontend can keep serving the dashboard with stale-but-complete data while no runtime exists; cells can allowlist the frontend\'s browser origins for live shard access with credentialed CORS' },
      { kind: 'added', textKey: "patchNotes.release.2.3.0.text.11260c51850b",
        text: 'A Reconnect control in the Command Center header (session.reconnect intent) forces a fresh game connection while a session is reconnecting, cooling down, suspended, or released, and the header now names suspended and released sessions with their resume time' },
      { kind: 'added', textKey: "patchNotes.release.2.3.0.text.651bf876cb36",
        text: 'Hosted assignments carry an on-disconnect policy: release, the hosted default, makes the runtime\'s lifetime follow the game connection, while hold (explicit) keeps the runtime reconnecting on its own like the desktop — after a short immediate retry window it reports the session as released with the earliest retry time (cooldown or suspension end, never sooner than the relog delay) and stops, so the control plane can drain it, give the slot to another account, and create a fresh runtime when the wait elapses or the user presses Reconnect; the control plane can also force a reconnect on a running runtime' },
      { kind: 'added', textKey: "patchNotes.release.2.3.0.text.a2d6b7ab8047",
        text: 'Hosted orchestration can install or rotate a runtime\'s game login and server selection through an epoch-fenced no-store control request that is written only to that runtime\'s protected saved-login file and never echoed, logged, or carried in reconcile, status, or event payloads, and can scrub it again before relocation or deletion; cell status now reports the current login obstacle as the raw game login code classified from the official client\'s error constants (20 invalid password, 21/26/368 wrong server, 27 suspended with the remaining suspension time or deactivated, 409/423 invalid login token, 453 cooldown) plus cooldown and retry times, so the control plane can wait out a lockout, hand a suspended or refused account back to the user, or re-place a runtime with the stored credential' },
      { kind: 'added', textKey: "patchNotes.release.2.3.0.text.43760a4f84eb",
        text: 'Dynamic hosted runtimes can publish one merged private My Stats and Feature Stats sample through an explicitly configured CitadelOpsBackend ingest contract while the ordinary desktop and static canary remain non-publishing by default' },
      { kind: 'added', textKey: "patchNotes.release.2.3.0.text.e743624c86f6",
        text: 'A game server directory now maps every official world code to its real connection address and zone — including worlds that share one multi-zone host, such as GB1, INT1, and SK1, which previously could not connect at all — sourced from the game\'s own network config, embedded as a snapshot, refreshable at runtime, and served to login forms at GET /api/v2/session/game-servers; the Settings server field suggests the official worlds by name' },
      { kind: 'added', textKey: "patchNotes.release.2.3.0.text.de81534c310e",
        text: 'Hosted login installs may pin the world\'s resolved connection address and zone from the control plane\'s shared directory, which the runtime validates against the official host shape and prefers over its own catalog, so a world opened after this build ships still connects without a release' },
      { kind: 'added', textKey: "patchNotes.release.2.3.0.text.6900f1f20711",
        text: 'Auto Khan now has independent controls for automatic camp attacks and full-rage retaliation, allowing attack-only operation or cooldown, rage, and defense maintenance around a manually driven Khan chain' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.0.text.1961f4fbc373",
        text: 'Exact command-response waiters now complete by frame ingress identity even when a successful protocol response has no retained state projection and intentionally creates no revision' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.0.text.33e601d7ddd6",
        text: 'Dashboard state changes apply sparse component and keyed-entry deltas instead of fetching and replacing the complete account state after every revision' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.0.text.8ec24ee5d9df",
        text: 'Live commander availability now synchronizes from a connection-scoped movement snapshot marker and continues through sparse movement deltas instead of remaining stuck on the retired raw protocol counter' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.0.text.db704c309535",
        text: 'Shop purchase counters are cached by castle and kingdom, so Luna, Auto Buyer, and construction-shop responses cannot overwrite one another or trigger a rapid cross-kingdom refresh loop' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.0.text.b41c51a316dd",
        text: 'Grouped state persistence now carries every dirty ID and shard key through the complete batch, preventing a later unrelated revision from turning one map or cooldown update into a full partition rewrite' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.0.text.b6eb46d4e244",
        text: 'Equipment target applicability now follows the official area and fight-scope fields across Effective Battle Report, Reconfigure, and Battle Stats, preventing PvP and castle-lord effects from being counted for Rift Raid area 43' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.0.text.d988003bad28",
        text: 'World Intelligence subscribers receive every stored row as one complete selected-leaderboard base followed by shared upserts and removals, with compact world revisions and a bounded metadata fallback replacing the former twelve-run response fanout' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.0.text.cca7a652e0e0",
        text: 'Standalone desktop builds skip absent typed-nil automation policies, preventing live game frames from crashing Amos when hosted shared Storm coordination is unavailable' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.0.text.fa6920e25e0b",
        text: 'Dashboard commands no longer live or die with the dashboard connection: intents are accepted immediately and executed by the runtime under its own lifetime, completion streams through operation events with a polling fallback, and closing the tab, sleeping, losing the network, or a hosted gateway timeout can no longer cancel a running operation; POST /api/v2/intents/{name} now answers 202 with the accepted receipt unless ?wait=true asks for the final one' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.0.text.069c5a4c84e4",
        text: 'Private metrics retries now classify the backend answer: transient failures replay the identical sample under the same idempotency key with capped jittered backoff and Retry-After, a durably rejected sample is dropped so the next cadence publishes a fresh one instead of blocking the runtime until the next reconcile, and a refused grant stops being spent until orchestration rotates it' },
      { kind: 'fixed', textKey: "patchNotes.release.2.3.0.text.b5293281c249",
        text: 'Auto Nomad and Samurai now size troop and tool requirements from the camp-capacity-adjusted event preset and keep leveling with every available commander instead of waiting for each earlier camp victory' },
      { kind: 'security', textKey: "patchNotes.release.2.3.0.text.5456a8871273",
        text: 'Orchestrator credentials and short-lived dashboard connection grants are separate, stored only as hashes in process memory, fenced by desired revision and placement epoch, and bound to one exact runtime shard; route mismatches return not found and token rotation invalidates older dashboard sessions' },
      { kind: 'security', textKey: "patchNotes.release.2.3.0.text.e4081767515b",
        text: 'Private metrics require a unique short-lived in-memory grant for one tenant, runtime, cell, placement epoch, and lease; grants never enter payloads or status streams, cannot be shared across runtimes or reused for dashboards, and uploads wait for a matching authoritative game identity and session generation' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.0.text.dcc0c14549b6",
        text: 'Game state keeps the official logical domain model while high-cardinality map, movement, castle, inventory, Storm, tower, report, event-score, and attack-analytics data uses selective immutable copy-on-write partitions shared by the desktop and isolated hosted-runtime compositions' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.0.text.58e898ee9f7c",
        text: 'Reducer ownership and automation wakes are targeted across every state domain: mixed protocol envelopes publish only projections that changed, while disabled or unchanged policies wait for an exact domain, configuration, session, or scheduled deadline instead of being rescanned every coordinator tick' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.0.text.395aaebf51cf",
        text: 'Luna counter refreshes are limited to a completed purchase response or an expired five-minute castle snapshot, while Auto Buyer evaluates at most every 30 minutes and refreshes its shop counters at most hourly' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.0.text.b7894f7060ed",
        text: 'Limited-time automation lanes sleep after the authoritative daily event check when their event is unavailable; Auto Buyer skips only the affected event-shop goals while continuing ordinary shops, specialists, and feasts' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.0.text.f68a5698ba2d",
        text: 'State recovery now group-commits only dirty components, IDs, parts, or physical shards on a fixed window, while retaining migration from the legacy complete GameState snapshot' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.0.text.915eb95f1e0d",
        text: 'Unknown map object types and protocol observations are decoded transiently but retained only after an explicit consumer-backed projection is registered, with bounded map retention for supported types' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.0.text.32efed76452c",
        text: 'Raw game telemetry keeps the complete wire stream on disk while using byte-bounded in-memory tails, amortized constant-time retention, and grouped buffered writes to reduce allocation, copying, and filesystem overhead' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.0.text.8725b1e9ba8b",
        text: 'Immutable Storm, crafting, resource, currency, building, construction-item, unit, and subscription-effect catalog projections are decoded and indexed once per official data version instead of repeatedly parsing the same JSON during automation evaluation' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.0.text.ab4e4953ac3a",
        text: 'The redundant Local desktop control footer was removed from the sidebar' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.0.text.cdb0d095ef43",
        text: 'Dashboard HTTP, event-stream, and WebSocket URLs derive the authenticated runtime shard from the hosted account path, while desktop URLs remain unchanged at the root API path' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.0.text.a4c3a6cf78c9",
        text: 'Background sessions now stay connected for as long as the account is enabled: every drop reconnects after the user\'s relog delay, a login cooldown waits out the game\'s timer plus that delay, a temporary suspension reports suspended and resumes by itself when it ends, an unknown login code retries with a doubling delay capped at one hour, and only invalid credentials, a wrong server selection, a permanent suspension, or a deactivated account park the session until the saved login changes, at which point Start no longer needs a preceding Stop' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.0.text.8ed2a912e6dc",
        text: 'Hosted account runtimes are long-lived: a runtime and its game session persist for as long as the account remains in the desired set, a lapsed placement lease only pauses private metrics publishing and dashboard-grant renewal while being reported as lapsed instead of draining the runtime, and only a reconcile that omits the account (or an explicit session stop) ends it, so a control-plane outage or missed reconcile can no longer log a hosted account out' },
      { kind: 'changed', textKey: "patchNotes.release.2.3.0.text.56967c15e5f3",
        text: 'Each hosted runtime keeps a compact in-memory projection of its attacker report history keyed to the analytics store write generation, so a steady-state private metrics sample rolls its 24-hour, 7-day, 30-day, and lifetime feature windows in under a millisecond instead of re-reading and decoding up to ten thousand report rows every minute; refreshes use a narrow attacker-only query, one publish attempt is bounded by a timeout, and placement rotation follows the regular cadence instead of bursting an extra upload from every runtime in the cell' },
      { kind: 'removed', textKey: "patchNotes.release.2.3.0.text.e4141b4c9695",
        text: 'Per-revision deep cloning, persistence cloning, and dashboard retransmission of the complete game state were removed from normal runtime processing' },
    ],
  },
  {
    version: '2.2.1',
    subtitleKey: "patchNotes.release.2.2.1.subtitle.0f214d6b37a8",
        subtitle: 'Title-aware recruiting, independent Background login, and safer automation decisions',
    date: '2026-08-13',
    items: [
      { kind: 'added', textKey: "patchNotes.release.2.2.1.text.1933e5719282",
        text: 'Background mode can now be configured directly with a game username, password, and world code, then connect without first capturing a Full application session; the current official client build and remaining WebSocket handshake values are derived automatically' },
      { kind: 'added', textKey: "patchNotes.release.2.2.1.text.94aeb734544d",
        text: 'Auto Recruit now tracks the current Glory and Gallantry titles from live game updates while keeping the two title systems independent; only the active connection\'s observed Glory title can authorize Glory-title recruits' },
      { kind: 'added', textKey: "patchNotes.release.2.2.1.text.5d3df00df6df",
        text: 'A new off-by-default Recruit level 10 if glory title is lost option can queue the corresponding level 10 unit after title loss; while it is off, affected slots are softly paused and rotating schedules continue with another available slot' },
      { kind: 'fixed', textKey: "patchNotes.release.2.2.1.text.4ac4a76e1f38",
        text: 'Auto Bird retains castle focus from its final source refresh through dispatch and respects each castle\'s retry window, preventing focus races, rapid back-and-forth preparation, and one waiting castle from blocking another castle\'s cycle' },
      { kind: 'fixed', textKey: "patchNotes.release.2.2.1.text.743c612684a2",
        text: 'The authoritative daily attack count is refreshed on a bounded interval after the server maximum is reached, so attack automations can resume after the game resets the count without unrelated policy churn' },
      { kind: 'fixed', textKey: "patchNotes.release.2.2.1.text.d297b8066b88",
        text: 'Spy reports now preserve official wall, gate, moat, keep, tower, general, and general-ability fields instead of interpreting unrelated packet values as calculated defense percentages' },
      { kind: 'fixed', textKey: "patchNotes.release.2.2.1.text.0a2811519b26",
        text: 'Horse travel boosts fail closed when placed building data does not identify one active compatible building set, avoiding a travel selection based on ambiguous stable, faction-stable, or harbor state' },
      { kind: 'security', textKey: "patchNotes.release.2.2.1.text.550cf8dfa0d9",
        text: 'Background credentials are kept in a separate protected profile file, excluded from settings exports, API responses, receipts, and logs, and can only be changed through a size-bounded same-origin local request' },
      { kind: 'changed', textKey: "patchNotes.release.2.2.1.text.18292993484e",
        text: 'Level 11 Protector of the North and Valkyrie Sniper selections are checked against their official Glory-title unlocks whenever Auto Recruit plans a queue and again immediately before each recruit command' },
      { kind: 'changed', textKey: "patchNotes.release.2.2.1.text.a6873ebfb094",
        text: 'Recruit selections and weekly schedules now follow official unit upgrade families and automatically choose the highest member that the target castle currently exposes, while queue capacity and scheduled selections are revalidated before enqueueing' },
      { kind: 'changed', textKey: "patchNotes.release.2.2.1.text.731a01b449de",
        text: 'Storm Food and Mead kingdom deliveries now use a configurable minimum shipment of at least 10,000 after transport tolls, with 10,000 as the default' },
      { kind: 'changed', textKey: "patchNotes.release.2.2.1.text.be48c6c893c8",
        text: 'World Intelligence desktop access is now a read-only facade over the shared CitadelOps backend event, ranking, player, and alliance data; obsolete local catalog collection, scheduling, and storage were removed' },
      { kind: 'changed', textKey: "patchNotes.release.2.2.1.text.8a62db0bcd59",
        text: 'Experimental battle prediction now uses the catalog-effect combat v2 model with per-wave and per-lane forces, tools, capped equipment and skill effects, fortification levels, courtyard control, and explicit uncertainty for hidden defender tools' },
    ],
  },
  {
    version: '2.2.0',
    subtitleKey: "patchNotes.release.2.2.0.subtitle.c0bfef58d55b",
        subtitle: 'Guarded Auto Buyer controls and unified event-aware World Intelligence',
    date: '2026-08-11',
    items: [
      { kind: 'added', textKey: "patchNotes.release.2.2.0.text.6617e9f87b68",
        text: 'Auto Buyer can purchase explicitly selected stock-limited items from supported merchants and active event shops, maintain fixed-price specialists at a user-selected floor of at least 14 days, and keep food or ruby feasts above a selected remaining-time floor' },
      { kind: 'changed', textKey: "patchNotes.release.2.2.0.text.92f8ca114a9e",
        text: 'Auto Buyer shop items are now selected through a focused shop dropdown with currency filtering, substring search, official localized package and price names, and a per-reset purchase limit that can be lower than the available stock' },
      { kind: 'security', textKey: "patchNotes.release.2.2.0.text.c3d7d8f4ff5d",
        text: 'Every automatic purchase rechecks its official catalog entry, live stock or timer state, event availability, balances, reserves, ruby ceilings, and configured purchase limit immediately before spending, then verifies the resulting server counter or timer' },
      { kind: 'changed', textKey: "patchNotes.release.2.2.0.text.d2842b6928af",
        text: 'Timed account offers remain disabled for unattended purchase until offer-item matching and the server-quoted ruby confirmation can be enforced end to end' },
      { kind: 'added', textKey: "patchNotes.release.2.2.0.text.e02d06d803e4",
        text: 'World Intelligence now consumes the backend event-run and event-score history contract, including occurrence identity, rank-only observations, score units, public event titles, and level-league metadata' },
      { kind: 'changed', textKey: "patchNotes.release.2.2.0.text.86cd68a6ba87",
        text: 'World rankings now use one event-aware table with permanent Name, Might, Honor, and Alliance columns plus Rank and Score for the selected event; every header is sortable and player or alliance search matches any substring' },
      { kind: 'changed', textKey: "patchNotes.release.2.2.0.text.2db08e1b48c0",
        text: 'Event selection uses human-readable public titles without exposing board IDs, adds Storm Islands rankings, and shows a level-league selector only for events that need one while defaulting to the viewing player\'s current league' },
      { kind: 'removed', textKey: "patchNotes.release.2.2.0.text.ccc23836e5ca",
        text: 'The official definition-catalog browser and separate regular-versus-event ranking tables were removed from World Intelligence in favor of the unified public leaderboard' },
      { kind: 'changed', textKey: "patchNotes.release.2.2.0.text.7ced740f5d20",
        text: 'Player dossiers now place localized public titles and relevant profile facts in the header, remove raw player IDs and redundant profile or observation-history sections, and add chartable Storm metrics beside Might, Loot, Glory, and Honor' },
      { kind: 'fixed', textKey: "patchNotes.release.2.2.0.text.2e0cf5abbada",
        text: 'Alliance dossiers are restored as full graph-driven views with Combined Might and Members history, 24-hour through all-time ranges, public event activity, holdings, and the observed roster' },
    ],
  },
  {
    version: '2.1.3',
    subtitleKey: "patchNotes.release.2.1.3.subtitle.65712307f83e",
        subtitle: 'Official World Intel catalogs, selectable public datasets, and clearer historical dossiers',
    date: '2026-08-09',
    items: [
      { kind: 'added', textKey: "patchNotes.release.2.1.3.text.5995d3cfd676",
        text: 'World Intelligence now collects versioned Storm thresholds, ranking and league definitions, gacha pull rules, event scoring, reward brackets, and referenced reward definitions from the same official Goodgame Studios CDN used for CitadelOps game data' },
      { kind: 'added', textKey: "patchNotes.release.2.1.3.text.d4bc18b02d39",
        text: 'The World Intelligence table includes a searchable public-dataset selector and renders every collected official category with source version, row coverage, contributor count, and stored version history' },
      { kind: 'changed', textKey: "patchNotes.release.2.1.3.text.d7c5b44ecb3d",
        text: 'Only the configured Adolphus Murtry and James Holden profiles contribute official catalog snapshots; Amos Burton remains a read-only viewer, and collection no longer requires a connected or baseline-synchronized game session' },
      { kind: 'removed', textKey: "patchNotes.release.2.1.3.text.9751a5789ecb",
        text: 'World Intelligence no longer sends game-socket leaderboard commands or builds scheduled observations from local account state' },
      { kind: 'fixed', textKey: "patchNotes.release.2.1.3.text.afa4ed060a4e",
        text: 'Player and alliance dossiers retain a visible back button and full-page navigation while preserved historical observations remain available below the official catalog view' },
    ],
  },
  {
    version: '2.1.1',
    subtitleKey: "patchNotes.release.2.1.1.subtitle.e27f95494a73",
        subtitle: 'Reliable Berimond construction, schedule-driven recruiting, corrected tool limits, and Background login recovery',
    date: '2026-08-06',
    items: [
      { kind: 'fixed', textKey: "patchNotes.release.2.1.1.text.ce7a991fd7cc",
        text: 'Auto Beri construction now preserves the live Berimond event context, so the built-in complete camp target can continue upgrading every camp and tent family to its official maximum WoD while respecting the selected Stable level' },
      { kind: 'fixed', textKey: "patchNotes.release.2.1.1.text.d2f1e273b9a1",
        text: 'Auto Recruit now resolves the active schedule option every time a queue slot opens, enqueues one scheduled stack, and reevaluates before filling another slot instead of falling back to the static configured unit' },
      { kind: 'fixed', textKey: "patchNotes.release.2.1.1.text.1e436e8e81eb",
        text: 'Attack preset tool limits now keep PvE at 30 / 40 / 30, use 40 / 50 / 40 for legendary PvP, and apply the logged-in player\'s official Hall tool bonus only to the flanks, allowing 50 / 50 / 50 when unlocked' },
      { kind: 'fixed', textKey: "patchNotes.release.2.1.1.text.aba66d3ea98a",
        text: 'Background mode now validates and explicitly re-enables an existing protected saved login when selected, offers an in-place recovery action when an earlier Full-mode page close incorrectly disabled it, and reconciles a fresh authoritative baseline when login and bootstrap frames arrive nearly simultaneously' },
    ],
  },
  {
    version: '2.1.0',
    subtitleKey: "patchNotes.release.2.1.0.subtitle.90ac4f3e3196",
        subtitle: 'Community-built world intelligence, cloud rankings, and public player and alliance history',
    date: '2026-08-05',
    items: [
      { kind: 'added', textKey: "patchNotes.release.2.1.0.text.8006004c0a86",
        text: 'World Intelligence adds cloud-backed player and alliance search, rankings, profiles, metric history, roster views, holdings, dataset coverage, and freshness indicators without relying on GGE-Tracker' },
      { kind: 'added', textKey: "patchNotes.release.2.1.0.text.75c4ca604156",
        text: 'Desktops can contribute bounded public observations through a durable private outbox; account credentials, resources, currencies, troops, inventory, movements, reports, raw game traffic, and protection details are never included' },
      { kind: 'added', textKey: "patchNotes.release.2.1.0.text.bf52ecdfb9c9",
        text: 'An explicitly opted-in Experimental Battle Prediction Calculator can save low-confidence pre-impact estimates and completed forward-test trials for outgoing PvP attacks you launch; it never launches attacks and clearly warns that its automatic spy missions use game resources' },
      { kind: 'added', textKey: "patchNotes.release.2.1.0.text.8ecb82e74ee8",
        text: 'Auto Beri now starts from a built-in complete camp target, resolves every camp and tent family to the current official maximum WoD, and lets each user choose Stable level 1 through 5' },
      { kind: 'changed', textKey: "patchNotes.release.2.1.0.text.343b365188c2",
        text: 'Alliance Targets now uses CitadelOps World Intelligence as its shared discovery source while retaining live in-game inspection for protection status' },
      { kind: 'changed', textKey: "patchNotes.release.2.1.0.text.8129924293c3",
        text: 'World Intelligence cloud access and public-data contribution are visible, independently configurable, and disabled by default until the desktop user explicitly enables them' },
    ],
  },
  {
    version: '2.0.2',
    subtitleKey: "patchNotes.release.2.0.2.subtitle.2732ed03de92",
        subtitle: 'Background operation, typed automation, bounded Rift runs, readable diagnostics, and safer event workflows',
    date: '2026-08-05',
    items: [
      { kind: 'added', textKey: "patchNotes.release.2.0.2.text.25f5c17d589d",
        text: 'Game Connection settings now offer both Full application and Background-only modes. Full mode keeps the complete playable game tab, while Background mode connects directly with substantially lower processor and memory use after one successful Full-mode sign-in' },
      { kind: 'added', textKey: "patchNotes.release.2.0.2.text.49b53a7e48b5",
        text: 'Background-only operation persists the selected startup mode, validates saved non-secret connection metadata, reconnects directly to the game server, and preserves the game\'s application heartbeat without opening Chromium' },
      { kind: 'added', textKey: "patchNotes.release.2.0.2.text.3b5d3db11db7",
        text: 'Rift Maiden probes accept an exact goal from 1 through 9,999, continue across commander-return rounds until that many launches are confirmed, show live progress, and can be cancelled without retracting attacks already sent' },
      { kind: 'added', textKey: "patchNotes.release.2.0.2.text.4aed1964e1d0",
        text: 'Auto Beri can capture durable functional, layout, or exact camp blueprints and build from confirmed returned loot without importing resources from another kingdom' },
      { kind: 'added', textKey: "patchNotes.release.2.0.2.text.c9f4ae587893",
        text: 'Auto Beri has an optional authoritative Gallantry-booster gate covering transfers, armorer purchases, camp setup, attacks, tools, and construction while preserving the separate booster setting' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.2.text.f936422047a6",
        text: 'Alliance Help is now a core live-session behavior instead of a feature toggle: CitadelOps answers actionable Help All requests even when every automation feature is off while preserving session readiness, deduplication, retry, and Bot Lock safeguards' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.2.text.1ac2a4ca253d",
        text: 'Rift Maiden launch, Berimond attack/build/tool lanes, Alliance Help, Storm construction, and other migrated workflows now declare typed resources and scoped read dependencies in the current intent engine' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.2.text.1a0d7ee14d80",
        text: 'Auto Food treats the Storm castle as a storage invariant: it keeps Food and Mead at observed capacity, never waits on troop consumption there, prioritizes Mead when both are low, and permits safe residual top-offs' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.2.text.b9dc4c5effcf",
        text: 'Auto Invasion, Auto Nomad, and Auto Advisor use the server-advertised event currencies and difficulties, preserving Bot Lock and failing closed when a requested live option is unavailable' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.2.text.4e4466e98a2e",
        text: 'Operation receipts, scoped resource claims, read sets, state persistence, movement timing, and production reconciliation now retain the context required for safe retries and multi-step automation' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.2.text.6fb43d8b0bfb",
        text: 'Castle, equipment, item, building, troop, tool, currency, effect, and other game identifiers are translated to user-facing names in intent failures, automation status, and activity messages whenever official labels are available' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.2.text.be9a786d50aa",
        text: 'Existing battle-report history is imported into the current SQLite report store with durable deduplication and compatibility handling' },
      { kind: 'fixed', textKey: "patchNotes.release.2.0.2.text.da828df3078a",
        text: 'Rift Maiden launches use the main castle and current Rift destination consistently, and exact-count runs no longer stop after only the commanders available in the first round' },
      { kind: 'fixed', textKey: "patchNotes.release.2.0.2.text.f58c116ffb59",
        text: 'Berimond attack admission, target refresh, tool preparation, booster gating, returned-loot construction, and lane isolation no longer block unrelated work or dispatch against stale context' },
      { kind: 'fixed', textKey: "patchNotes.release.2.0.2.text.3bc1249d2ebd",
        text: 'Storm food balancing no longer counts or waits for Storm troop consumption and no longer leaves small safe Food or Mead deficits below the ordinary minimum-shipment threshold' },
      { kind: 'fixed', textKey: "patchNotes.release.2.0.2.text.06d03432a6e8",
        text: 'Session banners, headers, runtime state, and settings now distinguish the configured connection mode from the active mode and clearly show when a restart is required' },
      { kind: 'fixed', textKey: "patchNotes.release.2.0.2.text.423dea8a81c4",
        text: 'Windows desktop launches now open operation and report databases correctly when the data directory is on a drive-letter or OneDrive path instead of exiting with an invalid SQLite URI authority error' },
    ],
  },
  {
    version: '2.0.1',
    subtitleKey: "patchNotes.release.2.0.1.subtitle.a84dfc71e274",
        subtitle: 'Material 3 Expressive interface, safer automation recovery, refined logistics, and bounded telemetry',
    date: '2026-08-03',
    items: [
      { kind: 'added', textKey: "patchNotes.release.2.0.1.text.fec57c430bb1",
        text: 'Material 3 Expressive visual system across the complete dashboard, with new light and dark color themes, tonal surfaces, expressive shapes, adaptive navigation, typography, and motion' },
      { kind: 'added', textKey: "patchNotes.release.2.0.1.text.dd9c928c671a",
        text: 'PvE and PvP attack-preset types with visible lane tool limits, Hall of Legends tool-bonus support, builder clamping, and authoritative send-time enforcement' },
      { kind: 'added', textKey: "patchNotes.release.2.0.1.text.3b4e8ab35e43",
        text: 'App-native rolling 48-hour telemetry retention with three-hour channel-log rotation, safe legacy-log compaction, and rotated-history support for tails and launch counters' },
      { kind: 'added', textKey: "patchNotes.release.2.0.1.text.a6112c16af6d",
        text: 'Auto Beri armorer restocking for configured wooden tools plus optional MS1 through MS7 troop-transfer skips, with each purchase and skip confirmed before continuing' },
      { kind: 'added', textKey: "patchNotes.release.2.0.1.text.df34610b5719",
        text: 'Auto Storm can explicitly unlock a selected official prebuilt Storm castle and runs Aquamarine shop goals in an independent lane from combat and castle maintenance' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.1.text.57bf956eeb2b",
        text: 'Auto Food Balance uses one-way, storage-aware routing, excludes Berimond from ordinary food logistics, tries alternate safe donors, and resolves selected market travel boosts from each castle’s placed Stable, Faction Stable, or Harbor' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.1.text.f1e6e0d3d491",
        text: 'Auto Storm now separates combat, shop, and build decisions; revalidates targets, resources, troop imports, construction state, and time-skip inventory before each committed action' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.1.text.00518e32a610",
        text: 'Auto Bird uses fresh per-castle troop inventory, cycle-scoped claims, and explicit stale-tracking cleanup so one castle’s recovery does not block unrelated automation' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.1.text.2f6aa0d7067c",
        text: 'Auto Nomad keeps separate Nomad and Samurai attack presets while preserving legacy preset settings during migration' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.1.text.6fd5951fee33",
        text: 'Automation retry, cooldown, focus, transport, and stale-plan handling is scoped to the affected lane or castle instead of globally delaying unrelated work' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.1.text.8a1f099567f7",
        text: 'Expected troop and equipment shortages are shown as warnings rather than fatal application errors while genuine command failures remain errors' },
      { kind: 'fixed', textKey: "patchNotes.release.2.0.1.text.c6893c672e45",
        text: 'Prevented the Commander view from crashing when older or partially hydrated equipment records contain null effects' },
      { kind: 'fixed', textKey: "patchNotes.release.2.0.1.text.a0634a3f1873",
        text: 'Auto Beri now refreshes unavailable targets, holds attack context through launch verification, keeps troop transfers focus-neutral, and recovers from stalled attack admission with bounded retries' },
      { kind: 'fixed', textKey: "patchNotes.release.2.0.1.text.f2612702d556",
        text: 'Berimond troop transfers reject Mead and Beef units, reconcile arrivals and consumed skips, and stop a skip chain when the game does not confirm a timer reduction' },
      { kind: 'fixed', textKey: "patchNotes.release.2.0.1.text.606a0ea37bc9",
        text: 'Auto Storm settings remain compatible with older runtime previews, and the frontend no longer crashes when newer troop-history fields are absent' },
      { kind: 'fixed', textKey: "patchNotes.release.2.0.1.text.f37a89d4bd98",
        text: 'Castle, movement, transport, attack analytics, and automation state updates now invalidate only their true dependencies, reducing stale decisions and unrelated policy wakeups' },
      { kind: 'removed', textKey: "patchNotes.release.2.0.1.text.2a950e87ecb4",
        text: 'Removed the remaining glass-morphism styling, translucent blur surfaces, and glow-based status treatment from the dashboard' },
    ],
  },
  {
    version: '2.0.0',
    subtitleKey: "patchNotes.release.2.0.0.subtitle.2d37d4203936",
        subtitle: 'Canonical automation, event operations, resource logistics, Storm blueprints, and desktop reliability',
    date: '2026-07-27',
    items: [
      { kind: 'added', textKey: "patchNotes.release.2.0.0.text.0f3b8ef6a088",
        text: 'Unified Automation workspace with authoritative live status, guarded operations, schedules, duration controls, and per-feature settings' },
      { kind: 'added', textKey: "patchNotes.release.2.0.0.text.ea3cb6771bd2",
        text: 'Auto Towers with per-castle target maps, cooldown tracking, commander selection, travel boosts, and independent nearest-target attacks' },
      { kind: 'added', textKey: "patchNotes.release.2.0.0.text.68173f504505",
        text: 'Auto Invasion for Foreign Lords and Bloodcrows with difficulty selection, score goals, target strengthening, presets, and guarded spending' },
      { kind: 'added', textKey: "patchNotes.release.2.0.0.text.012ead7a892d",
        text: 'Auto Nomad and Samurai chains plus one-run Auto Advisor support with event-specific presets, camp locking, cooldown skips, and score targets' },
      { kind: 'added', textKey: "patchNotes.release.2.0.0.text.5b11213f3e97",
        text: 'Auto Khan attack, cooldown, rage, taunt, defense, tool-restock, and protection lanes that can run concurrently without blocking one another' },
      { kind: 'added', textKey: "patchNotes.release.2.0.0.text.6077f51f3ac3",
        text: 'Auto Storm fort and resource-island operations, troop transfers, Aquamarine goals, durable castle blueprints, and construction or destruction time-skip controls' },
      { kind: 'added', textKey: "patchNotes.release.2.0.0.text.fd3cd3820266",
        text: 'Auto Station threat response with explicit castle reserves, temporary troop evacuation, automatic recall, and optional open-gate fallback' },
      { kind: 'added', textKey: "patchNotes.release.2.0.0.text.18a988bc1633",
        text: 'Auto Sceat Resources with research-aware per-castle crafting plans, overflow handling, independent logistics, and kingdom storage buffers' },
      { kind: 'added', textKey: "patchNotes.release.2.0.0.text.4bd6fa822479",
        text: 'Auto Food Balance for Food, Honey, Mead, and Beef reserves using market barrows first and optional cross-kingdom transport with time skips' },
      { kind: 'added', textKey: "patchNotes.release.2.0.0.text.6bed6d171827",
        text: 'Dedicated Attack Presets with courtyard support troops, Sceat support tools, safe CRA-string import and sharing, plus Defense Presets and Feature Stats workspaces' },
      { kind: 'added', textKey: "patchNotes.release.2.0.0.text.e17ee0c90d5a",
        text: 'Header tracker for the authoritative account-wide daily normal-attack count plus optional user-defined limits on supported attack automations' },
      { kind: 'added', textKey: "patchNotes.release.2.0.0.text.fffa397cfa70",
        text: 'Settings import and export, browser selection, runtime diagnostics, and version-aware desktop update handling' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.0.text.5f59a16cb01d",
        text: 'Rebuilt CitadelOps around versioned state, configuration, history, telemetry, API, intent, catalog, and Chromium session contracts' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.0.text.0c4d4bf09e54",
        text: 'Auto Bird, Auto TCI, recruiting, tools, hospital, Berimond, Rift, and scheduling now use server-authoritative state with legacy settings migration' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.0.text.46dc38ec62c4",
        text: 'Resource logistics now supports capacity-bounded multi-resource sends, full donor availability, market barrows, immediate transport skips, and post-loot redistribution' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.0.text.79ae2c822fea",
        text: 'Crafting logistics runs independently from crafting queues and can source ready resources from any eligible castle instead of waiting on one configured castle' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.0.text.6b629ea15b85",
        text: 'Honey demand now uses each Brewery base rate and configured operating percentage instead of scaling from live Mead production' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.0.text.9faa0d501c49",
        text: 'Attack automation now coordinates live commander availability, exact event presets, movement returns, cooldowns, protection mode, and castle focus through guarded intents' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.0.text.de4e4cdca28c",
        text: 'Battle and spy reports now use canonical local analytics, safe cloud outboxes, PvP eligibility checks, report deduplication, and movement-aware training context' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.0.text.c274007d383f",
        text: 'Equipment effects, caps, compatibility, gems, set bonuses, construction items, buildings, units, and shops now resolve through current official game data' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.0.text.1bded4e8df5c",
        text: 'Alliance Targets keeps inspected rosters separate from the player alliance and derives travel, spy capacity, reports, and attack previews from canonical state' },
      { kind: 'changed', textKey: "patchNotes.release.2.0.0.text.dce4fcf410bf",
        text: 'Connection recovery now validates a fresh login and castle bootstrap before state-dependent automation resumes, including reused Chromium profiles and Auto Restore' },
      { kind: 'fixed', textKey: "patchNotes.release.2.0.0.text.54d7c598603a",
        text: 'Bounded stale-plan retries prevent repeated command refresh loops, while concurrent Auto Khan lanes prioritize full-rage taunts without blocking attack chains' },
      { kind: 'fixed', textKey: "patchNotes.release.2.0.0.text.7cae81579b01",
        text: 'Corrected Storm fort attack limits, commander release on reported return legs, crafting resource waits, and kingdom shipment settlement' },
      { kind: 'removed', textKey: "patchNotes.release.2.0.0.text.1918801b01ca",
        text: 'Removed automatic enforcement of the game 3,500-attack cost threshold; it remains informational unless the user sets an explicit automation limit' },
      { kind: 'removed', textKey: "patchNotes.release.2.0.0.text.14236e54a6bb",
        text: 'Removed automatic game-panel closing after successful attack dispatch while preserving guarded pre-launch cleanup' },
      { kind: 'removed', textKey: "patchNotes.release.2.0.0.text.6f72d09508ea",
        text: 'Removed legacy raw WebSocket actions, client-only automation mirrors, UI-shaped compatibility adapters, and stale embedded catalog paths' },
    ],
  },
  {
    version: '1.3.7',
    subtitleKey: "patchNotes.release.1.3.7.subtitle.f1f6967acd0f",
        subtitle: 'Player analytics, alliance intelligence, equipment data, attack planning, and connection recovery',
    date: '2026-07-10',
    items: [
      { kind: 'added', textKey: "patchNotes.release.1.3.7.text.f7a3e9004f78",
        text: 'My Stats analytics with one-minute history for player scores, troops, currencies, and speedups' },
      { kind: 'added', textKey: "patchNotes.release.1.3.7.text.92227b8b76c9",
        text: 'Interactive trend charts with hover inspection, custom drag-selected time windows, rate-of-change summaries, and 24-hour, 7-day, 30-day, and all-time ranges' },
      { kind: 'added', textKey: "patchNotes.release.1.3.7.text.cedecf0ea60b",
        text: 'Troop analytics with type, role, and food filters plus top-unit trend lines and combat composition summaries' },
      { kind: 'added', textKey: "patchNotes.release.1.3.7.text.2fd6fd48062d",
        text: 'GGE Tracker backfill for supported player-history gaps while locally collected observations remain authoritative' },
      { kind: 'added', textKey: "patchNotes.release.1.3.7.text.80a67e3fb4b6",
        text: 'Commander roster and movement status tracking backed by reconciled game movement snapshots' },
      { kind: 'added', textKey: "patchNotes.release.1.3.7.text.ce2a9e32520a",
        text: 'Multi-wave attack planning with inventory-aware troop and tool allocation, reusable presets, and improved Rift launch handling' },
      { kind: 'added', textKey: "patchNotes.release.1.3.7.text.bc8c57353ee5",
        text: 'Commander and castellan base-equipment loadout swapping' },
      { kind: 'added', textKey: "patchNotes.release.1.3.7.text.51d536632478",
        text: 'Alliance target intelligence with castle selection, travel distance, spy availability, and live espionage launching' },
      { kind: 'added', textKey: "patchNotes.release.1.3.7.text.ad4c59f397a3",
        text: 'Alliance spy-report sharing with six-hour visibility, movement correlation, and battle-training context' },
      { kind: 'changed', textKey: "patchNotes.release.1.3.7.text.932cecc138ab",
        text: 'Equipment effects now use the latest official catalogs, localized labels, wearer-aware mappings, PvP and PvE scopes, caps, gems, and set bonuses' },
      { kind: 'changed', textKey: "patchNotes.release.1.3.7.text.6abf70a83879",
        text: 'Effective Battle Profile now shows every applicable always-on plus PvP or PvE total instead of an eight-stat preview' },
      { kind: 'changed', textKey: "patchNotes.release.1.3.7.text.79e8f4f44565",
        text: 'Game connection status and retry handling now provide consistent login, cooldown, reconnecting, and stale-session state across the dashboard' },
      { kind: 'changed', textKey: "patchNotes.release.1.3.7.text.0004bb9c5bb8",
        text: 'Automation features coordinate castle focus so manual actions and higher-priority tasks do not compete for the active castle' },
      { kind: 'fixed', textKey: "patchNotes.release.1.3.7.text.2a9995d44a9a",
        text: 'Improved Auto Bird, Auto TCI, recruiting, tool, hospital, movement, and castle-state synchronization during refreshes and reconnects' },
    ],
  },
  {
    version: '1.3.6',
    subtitleKey: "patchNotes.release.1.3.6.subtitle.e650aaec41a7",
        subtitle: 'Scheduler, recruiting, tools, hospital automation, subscription state, and interface refresh',
    date: '2026-07-02',
    items: [
      { kind: 'added', textKey: "patchNotes.release.1.3.6.text.cbd94862868d",
        text: 'Feature scheduling controls for automation windows and weekly run plans' },
      { kind: 'added', textKey: "patchNotes.release.1.3.6.text.f16416df8142",
        text: 'Recruit troops settings backed by production slot and capacity parsing' },
      { kind: 'added', textKey: "patchNotes.release.1.3.6.text.b797541e7799",
        text: 'Auto Tool settings with queueable tool catalog support' },
      { kind: 'added', textKey: "patchNotes.release.1.3.6.text.1cc51dd943db",
        text: 'Auto Hospital automation with hospital slot detection, subscription stack capacity, scan interval settings, and weekly scheduling' },
      { kind: 'added', textKey: "patchNotes.release.1.3.6.text.659a155ec6ff",
        text: 'Auto Hospital ruby-heal filtering that discards ruby-cost wounded units before queueing coin-healable units' },
      { kind: 'added', textKey: "patchNotes.release.1.3.6.text.7d5bdf971c39",
        text: 'Subscription and VIP state parsing for game-state snapshots' },
      { kind: 'changed', textKey: "patchNotes.release.1.3.6.text.17b53227b9ca",
        text: 'Updated dashboard, equipment, TCI, troop picker, logger, and sidebar surfaces for the refreshed UI' },
      { kind: 'changed', textKey: "patchNotes.release.1.3.6.text.b0dfa93202aa",
        text: 'Hospital, recruit, and tool queue parsing now keeps automation state aligned with live focused-castle responses' },
      { kind: 'fixed', textKey: "patchNotes.release.1.3.6.text.208c858c806c",
        text: 'Improved battle report and live equipment stat mapping coverage' },
    ],
  },
  {
    version: '1.3.3',
    subtitleKey: "patchNotes.release.1.3.3.subtitle.bdf4525830dd",
        subtitle: 'Offline snapshot UI; Auto Bird; decoration preset alerts',
    date: '2026-04-10',
    items: [
      { kind: 'added', textKey: "patchNotes.release.1.3.3.text.e441a949df91",
        text: 'Patch Notes: in-app changelog (System)' },
      { kind: 'added', textKey: "patchNotes.release.1.3.3.text.7c337b490855",
        text: 'Offline dashboard: last local snapshot — castles, resources, focus' },
      { kind: 'added', textKey: "patchNotes.release.1.3.3.text.06f5f72c97ad",
        text: 'Offline castle picker: full list from cached castles' },
      { kind: 'added', textKey: "patchNotes.release.1.3.3.text.e89a97619b56",
        text: 'Auto Bird: login gate; refresh if session not valid' },
      { kind: 'added', textKey: "patchNotes.release.1.3.3.text.3522f3e8d52f",
        text: 'Auto Bird: longer post-refresh login wait (~5 min) when game queue is long' },
      { kind: 'fixed', textKey: "patchNotes.release.1.3.3.text.b7e7495d22b7",
        text: 'Offline castle switch: UI matches last snapshot (avoids stale pre-disconnect values)' },
      { kind: 'fixed', textKey: "patchNotes.release.1.3.3.text.5fff445a08c1",
        text: 'Auto Bird + mid-session disconnect: refresh recovery path instead of idle until next run' },
      {
        kind: 'changed',
        textKey: "patchNotes.release.1.3.3.text.56d57fea65df",
        text: 'Decoration preset Apply: SOB/EBU step lines no longer show in the decorations panel — status is only in the global Alerts stack',
      },
      {
        kind: 'added',
        textKey: "patchNotes.release.1.3.3.text.8212919afe6c",
        text: 'Decoration preset apply: persistent “apply started” alert with Cancel apply; cleared when the run finishes, fails, is cancelled, or hits a storage shortfall',
      },
      {
        kind: 'added',
        textKey: "patchNotes.release.1.3.3.text.6d191bb55600",
        text: 'Preset storage shortfall: missing decorations listed as bullets (e.g. 1x Name) in a persistent red alert until dismissed or apply completes successfully',
      },
      {
        kind: 'changed',
        textKey: "patchNotes.release.1.3.3.text.dc721473c7cd",
        text: 'Server: decoration apply no longer spams internal sin/storage progress lines to the UI; shortfall uses display names aligned with decoration summaries',
      },
    ],
  },
];

export const PATCH_NOTES_RELEASES: PatchNotesRelease[] = PATCH_NOTES_RELEASES_UNSORTED.map((release) => ({
  ...release,
  items: sortPatchNoteItems(release.items),
}));

export const APP_VERSION_CURRENT = PATCH_NOTES_RELEASES[0].version;
