// Code generated by tools/GenConsumptionReduction; DO NOT EDIT.

package gamedata

// ConsumptionReductionByBuildingWodID maps building definition wodID → reduction PP (Bakery,
// BGBakery, MeadDistillery, ButcherShop). Regenerate from buildings/items.json via this tool.
var ConsumptionReductionByBuildingWodID = map[int]ConsumptionReductionPP{
	1868: {FoodPP: 5, MeadPP: 0, BeefPP: 0},
	1877: {FoodPP: 10, MeadPP: 0, BeefPP: 0},
	1878: {FoodPP: 15, MeadPP: 0, BeefPP: 0},
	1879: {FoodPP: 20, MeadPP: 0, BeefPP: 0},
	1880: {FoodPP: 25, MeadPP: 0, BeefPP: 0},
	798:  {FoodPP: 5, MeadPP: 0, BeefPP: 0},
	124:  {FoodPP: 10, MeadPP: 0, BeefPP: 0},
	799:  {FoodPP: 15, MeadPP: 0, BeefPP: 0},
	125:  {FoodPP: 20, MeadPP: 0, BeefPP: 0},
	800:  {FoodPP: 25, MeadPP: 0, BeefPP: 0},
	126:  {FoodPP: 30, MeadPP: 0, BeefPP: 0},
	801:  {FoodPP: 35, MeadPP: 0, BeefPP: 0},
	196:  {FoodPP: 40, MeadPP: 0, BeefPP: 0},
	4265: {FoodPP: 0, MeadPP: 0, BeefPP: 5},
	4266: {FoodPP: 0, MeadPP: 0, BeefPP: 10},
	4267: {FoodPP: 0, MeadPP: 0, BeefPP: 15},
	4268: {FoodPP: 0, MeadPP: 0, BeefPP: 20},
	4269: {FoodPP: 0, MeadPP: 0, BeefPP: 25},
	4270: {FoodPP: 0, MeadPP: 0, BeefPP: 30},
	4271: {FoodPP: 0, MeadPP: 0, BeefPP: 35},
	4272: {FoodPP: 0, MeadPP: 0, BeefPP: 40},
	4273: {FoodPP: 0, MeadPP: 0, BeefPP: 45},
	4274: {FoodPP: 0, MeadPP: 0, BeefPP: 50},
	2020: {FoodPP: 0, MeadPP: 5, BeefPP: 0},
	2021: {FoodPP: 0, MeadPP: 10, BeefPP: 0},
	2022: {FoodPP: 0, MeadPP: 15, BeefPP: 0},
	2023: {FoodPP: 0, MeadPP: 20, BeefPP: 0},
	2024: {FoodPP: 0, MeadPP: 25, BeefPP: 0},
	2025: {FoodPP: 0, MeadPP: 30, BeefPP: 0},
	2026: {FoodPP: 0, MeadPP: 35, BeefPP: 0},
	2027: {FoodPP: 0, MeadPP: 40, BeefPP: 0},
}
